### ISSUE TITLE
i18n - Locales not loaded?

### ISSUE THREAD

**Issue by HerveSeger** [stefanpenner/ember-moment#105]
Hi.

I am using ember-cli 1.13.8 and the latest release of ember-moment.

I need to handle French (`fr-ca`) and English (`en-ca`) locales so I did this in config/environment.js where the ENV object is populated with all the key/values:
``` js
// config/environment.js
ENV[ 'moment' ] = {
		includeLocales: [ 'en-ca', 'fr-ca']
	};
```

But English is the only locale available. I have tried several different ways to force the locale to switch to `fr-ca` and nothing happens.
It looks that the locales are not loaded so the default one (`en`) is picked up.

Could you please tell me what I am missing here?

**Update:**
The locales (`en-ca`, `fr-ca`) are correctly added to vendor.js so I have checked moment-format.js that I used to test my locales and it looks that the locale is just ignored.
In my template I have:
{{moment-format challenge.start_date 'DD MMMM YYYY' locale='fr-ca'}}

I have added some logging to moment-format.js:
![image](https://cloud.githubusercontent.com/assets/4807035/10025740/276354cc-6134-11e5-9eb3-292056cc55f6.png)

Should I not see `_abbr: 'fr-ca'` ?

**Comment by jasonmit** [comment]
Are you sure your apps not including two instances of moment?  Not by a computer to try and reproduce this.

**Comment by HerveSeger** [comment]
You are right.

We had a reference of the regular JS version of Moment in `ember-cli-build.js` that I have removed. 
The locales work as expected now.

Thanks a lot :)
