### ISSUE TITLE
How do I use Moment plugins with this?

### ISSUE THREAD

**Issue by marnen** [stefanpenner/ember-moment#111]
I'd like to use Moment plugins such as [twix](http://momentjs.com/docs/#/plugins/twix/) with ember-moment, but I can't figure out how to register them on the Moment object without installing a separate copy of Moment from the one managed by ember-moment. Is there a way of doing this?

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-cli-moment-shim is where you'll want to open the issue.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-moment-twix-example/commit/6fbaf847410b0e0a3da84ff0beaedff39f332f4a

I also don't see any problems with ember-moment + twix, so not sure what you're doing wrong but there is a simple app with it running.

**Comment by figwit** [comment]
For reference, this example project is missing the dependancy in `bower.json`. The `--save` flag is required, as in:

```sh
bower install twix --save
```
