### ISSUE TITLE
Load locale at runtime

### ISSUE THREAD

**Issue by mjuniper** [stefanpenner/ember-moment#112]
We have an app that needs to support 26 languages. I don't want every user to have to download all 26 languages so I want to request the locale with XHR in an instance initializer at runtime and load the locale into moment as described [here](http://momentjs.com/docs/#/i18n/changing-locale/).

As far as I can tell, this is not possible. Am I missing something?

**Comment by jasonmit** [comment]
```
import moment from 'moment';
moment.locale(...);
```

All the moment methods are available.  This functionality is provided via https://github.com/jasonmit/ember-cli-moment-shim

Is the feature you're looking for to optionally write the locale json files to the assets folder instead of `vendor.js`?

**Comment by jasonmit** [comment]
@mjuniper please test the ember-cli-moment-shim changes and then I'll pull them upstream into ember-moment

**Comment by mjuniper** [comment]
Sorry, we went a different direction so I haven't been watching this. But yes, that is what I was after. I'll try to take a look this week.

**Comment by jasonmit** [comment]
Okay, closing issue feel free to update with your findings.

**Comment by elidupuis** [comment]
I had an in-repo-addon that was copying moment's locale files into `dist`. I can verify that this update works as expected :clap:

**Comment by jasonmit** [comment]
Great, thanks for the update
