### ISSUE TITLE
How default global locale is set?

### ISSUE THREAD

**Issue by tubia** [stefanpenner/ember-moment#114]
Hi,
I'm using this add-on but I'm experiencing some issues with the i18n features.
Actually, I've included these locales in my `config/environment.js` (I report also the ember-i18n config for clarity although I know is not directly related):
```json
var ENV = {
    i18n: {defaultLocale: 'en'},
    moment: {includeLocales: ['en', 'it']}
}
```

With these settings, the default language, printing `{{moment-format date 'llll'}}` is always 'it'.
My browser was set on 'Italian' so I switched it to 'English' language but still I see only Italian as the output. Only removing Italian language from the `includeLocales` array, stop `ember server`, `rm -rf tmp` and then restarting the ember server returns to me the string in English language.

So my question is: how default global locale is set? Is it possible to manage it via `config/environment.js`?

Thank you!

**Comment by jasonmit** [comment]
Not through config/environment, though I could implement this would review a PR that implements this.

**Comment by ptraceur** [comment]
I have the same problem, with ember-cli 2.4

using this method: 
```js
// app/routes/applicaton.js
import moment from 'moment';

export default Ember.Route.extend({
  beforeModel() {
    // sets the application locale to Spanish
    moment.locale('es');
  }
});
```

How would you change your default locale nowadays?

**Comment by jasonmit** [comment]
Isolate the issue and push an example of an app with the bug to github.

**Comment by jasonmit** [comment]
@ptraceur you need to be going through the moment service to change the locale.  This is covered in the README here https://github.com/stefanpenner/ember-moment#globally-set-locale

@tubia `en` is bundled with momentjs by default so referencing it within `includeLocales` isn't needed.  It also seems the first locale to register data on momentjs is set as the default locale so in this case that is `it`.  This isnt' a side effect of ember-moment but just how momentjs behaves.

I recommend this approach https://github.com/stefanpenner/ember-moment#globally-set-locale to ensure the app locale is properly set.
