### ISSUE TITLE
Current date if variable is undefined

### ISSUE THREAD

**Issue by jelhan** [stefanpenner/ember-moment#115]
`{{moment-format}}` helper uses current date if an undefined variable is passed in. If `allowEmpty` is `true` it outputs "not definied" instead.

This bug was already discussed lately in #89 but not really spotted. If `null` is passed to `{{moment-format}}` it outputs "Invalid date" or - if `allowEmpty` is `true` - an empty string.

Reproduced this bug using ember-cli 1.13.8, ember 1.13.7 and ember-moment 4.1.0.

**Comment by btecu** [comment]
`allowEmpty` can be passed on the helper itself, like `{{ember-moment myDate allowEmpty=true}}` and it works, except it logs out a warning: `ember-moment: an empty value (null, undefined, or "") was passed to moment-format`.
