### ISSUE TITLE
Service cannot be injected

### ISSUE THREAD

**Issue by manuel-reil** [stefanpenner/ember-moment#117]
Hi,

thanks for ember-moment.

I would like to inject the moment service into a controller in order to switch locales along with ember-i18n switching.

However, 'moment: Ember.inject.service' leads to 'Attempting to inject an unknown injection: `service:moment`' - whether I am trying to inject it in the controller or the application route.

What am I doing wrong?
Thank you.

**Versions:**
* Ember : 1.13.10
* Ember Data : 1.13.13
* jQuery : 2.1.4

**Comment by jasonmit** [comment]
Hmm, you're sure ember-moment is in your package.json?

**Comment by manuel-reil** [comment]
In my pain, I did the equivalent of an "Windows 95 reboot" and cleared out the tmp folder. Then it worked.
Btw. with every file change and ember server refresh, less services were succesfully injected...

Sorry for raising it as an issue. I had the feeling that something fundamentally was broken in the component.
