### ISSUE TITLE
Use from Addon?

### ISSUE THREAD

**Issue by spinlock99** [stefanpenner/ember-moment#120]
I'm trying to use `ember-moment` in an addon that I'm developing and I'm having some issues getting it to work.

For my development setup, I'm using `npm link` to access the addon from my project:

    ~my-addon$ npm link
    ~/project$ npm link my-addon

but, when I try to import `momentFromNow` into my addon:

    import momentFromNow from 'ember-moment/computeds/from-now';

I get the following error:

    Uncaught Error: Could not find module `ember-moment/computeds/from-now` imported from `my-addon/components/moment-from-now`

Any idea how to make this work?

Thanks!

**Comment by jasonmit** [comment]
Add ember-moment in your package.json also.  That's the source of truth for how ember-cli loads the addons, not the fact that they're installed or symlinked in node_modules.

**Comment by spinlock99** [comment]
`ember-moment` is added to the addon's `package.json`. I got this working by adding it to the project's `package.json` as well. Is that what you mean? I think I need to add a generator to my addon to add `ember-moment` to the project's dependencies. 

Does that sound right?

Thanks.

**Comment by jasonmit** [comment]
@spinlock99 yes, an example of that https://github.com/stefanpenner/ember-moment/blob/master/blueprints/ember-moment/index.js#L11
