### ISSUE TITLE
Configurable default date format

### ISSUE THREAD

**Issue by mydea** [stefanpenner/ember-moment#121]
Right now, it is possible to set a global default format in `config/environment.js`. 

It would be really nice if the default format could be a changable value, e.g. on the moment service. In my app, users can choose & save a date format which is then used in the app. It would be really useful to have something like:

```js
this.get('moment').changeDefaultFormat("DD.MM.YYYY");
```

And have all moment-format helpers update themselves automatically, similar to `changeLocale` and `changeTimeZone`. Without this, I'm stuck injecting my userSession service everywhere where I'm using moment-format (which is pretty much everywhere) and manually setting it manually: 

```hbs
{{moment-format myDate userSession.dateFormat}}
```

**Comment by jasonmit** [comment]
Agreed, would happily review a PR for this

**Comment by jasonmit** [comment]
@mydea I tweaked the logic a bit in my PR #124 and wrote a test to cover
