### ISSUE TITLE
locale trouble

### ISSUE THREAD

**Issue by acerov** [stefanpenner/ember-moment#132]
Hi there,
I can't get locale to work, it is allways "en"
tried:
`// app/routes/applicaton.js`
`import moment from 'moment';`
`export default Ember.Route.extend({`
`  beforeModel() {`
`    moment.locale('hr');`
`  }`
`});`

also:
`// app/routes/applicaton.js`
`export default Ember.Route.extend({`
  `moment: Ember.inject.service(),`
  `beforeModel() {`
    `this.get('moment').changeLocale('hr');`
  `}`
`});`

in environment I have:
    `moment: {`
      `outputFormat: 'L',`
      `includeLocales: ['en', 'hr']`
    `}`

**Comment by jasonmit** [comment]
There is a good chance you have another addon, or your app itself, is importing momentjs.

**Comment by acerov** [comment]
@jasonmit i had "ember-cli-moment": "0.0.2", I removed it from "package.json" but still no change
If I do:
`moment.locale("hr");`
`console.log(moment.locale());` //output is "en"

**Comment by acerov** [comment]
If I set locale with complete locale object then it works
`moment.locale('hr', {months : ... etc})`

**Comment by jasonmit** [comment]
@acerov every time this issue pops up it turns out it was another addon `app.import`ing momentjs.  Please check your package.json for other addons that might be doing this and your own `ember-cli-build.js` file for an app.import on moment.

**Comment by acerov** [comment]
@jasonmit thank you for your time on this,
I double checked `ember-cli-build.js` there is no `moment`
My package.js dependencies is bellow (`ember-cli-moment-shim` is in):
  `"devDependencies": {`
    `"broccoli-asset-rev": "^2.1.2",`
    `"broccoli-manifest": "0.0.7",`
    `"broccoli-merge-trees": "^0.2.3",`
    `"broccoli-serviceworker": "0.0.5",`
    `"ember-async-button": "^0.7.0",`
    `"ember-bootstrap-datetimepicker": "1.0.2",`
    `"ember-browserify": "^1.0.5",`
    `"ember-cli": "1.13.8",`
    `"ember-cli-app-version": "1.0.0",`
    `"ember-cli-babel": "^5.1.3",`
    `"ember-cli-chart": "2.0.5",`
    `"ember-cli-content-security-policy": "0.4.0",`
    `"ember-cli-dependency-checker": "^1.0.1",`
    `"ember-cli-deploy": "^0.5.1",`
    `"ember-cli-deploy-build": "0.1.0",`
    `"ember-cli-deploy-chrome-app": "0.1.4",`
    `"ember-cli-filter-by-query": "1.1.3",`
    `"ember-cli-filter-component": "2.0.1",`
    `"ember-cli-form-data": "0.1.1",`
    `"ember-cli-full-calendar": "0.0.9",`
    `"ember-cli-htmlbars": "0.7.9",`
    `"ember-cli-htmlbars-inline-precompile": "^0.2.0",`
    `"ember-cli-ic-ajax": "0.2.1",`
    `"ember-cli-inject-live-reload": "^1.3.1",`
    `"ember-cli-moment-shim": "0.7.1",`
    `"ember-cli-notifications": "2.1.4",`
    `"ember-cli-qunit": "^1.0.0",`
    `"ember-cli-release": "0.2.3",`
    `"ember-cli-simple-auth": "0.8.0",`
    `"ember-cli-simple-auth-token": "^0.7.3",`
    `"ember-cli-spinjs": "1.0.2",`
    `"ember-cli-spinkit": "1.0.0",`
    `"ember-cli-sri": "^1.0.3",`
    `"ember-cli-uglify": "^1.2.0",`
    `"ember-cli-uploader": "^0.3.11",`
    `"ember-data": "1.13.15",`
    `"ember-data-offline": "0.2.0",`
    `"ember-disable-proxy-controllers": "^1.0.0",`
    `"ember-export-application-global": "^1.0.3",`
    `"ember-i18n": "4.1.2",`
    `"ember-infinity": "0.2.0",`
    `"ember-localforage-adapter": "2.2.0",`
    `"ember-models-table": "1.4.1",`
    `"ember-moment": "4.2.1",`
    `"ember-power-select": "0.7.0-beta.6",`
    `"ember-searchable-select": "0.6.3",`
    `"ember-select-2": "1.3.0",`
    `"ember-spinner-button": "0.0.10",`
    `"ember-table": "0.9.2",`
    `"handlebars": "^1.3.0",`
    `"install": "^0.1.8",`
    `"npm": "^3.3.6"`
  `},`

**Comment by jasonmit** [comment]
`ember-cli-full-calendar` is likely the problem.

https://github.com/icicletech/ember-cli-full-calendar/blob/97a63ec97cb21889d51b807f767d50780fd93e08/index.js

**Comment by jasonmit** [comment]
@stefanpenner do you see anything wrong ember-cli-moment-shim closing over `app.import` to warn if any other parts of the app attempt to import moment?  This keeps resurfacing and not sure how to prevent it.

If I were able to ensure the addon would be pushed to the furthest edge of the DAG then I guess that would also solve it, but would require buy-in for this to be supported in ember-cli.

**Comment by acerov** [comment]
@jasonmit :+1: I updated to `"ember-cli-full-calendar": "0.0.17"` and it works now.
Is that related to https://github.com/icicletech/ember-cli-full-calendar/commit/11475e7c4beec93958f8134416fd7c8f30bfc72e ?
