### ISSUE TITLE
shortDate: momentFormat('date', 'MM/DD/YYYY') error

### ISSUE THREAD

**Issue by haldiggs** [stefanpenner/ember-moment#133]
I'm sure this is just an issue with my configuration... after adding this addon moment seems to work fine, moment() does get a date. However I am trying out some of the examples and when I try to use

    import momentDuration from 'ember-moment/computeds/duration';
    
    in a controller
    computedNumHours: momentDuration(10, 'hours')
just produces

"TypeError: pattern.indexOf is not a function"

**Comment by jasonmit** [comment]
Confirming it's a bug, and will patch it tonight.

**Comment by haldiggs** [comment]
cool... so since I loaded this using 'ember install' (forgive me as I try to figure this out), I know I can replace the code locally, how does it get up onto the ember listing? more curious than anything else

**Comment by jasonmit** [comment]
@haldiggs I'm not sure the question, you want to pull in my branch with the patch?

**Comment by jasonmit** [comment]
Versioned as 5.0.0
