### ISSUE TITLE
Computeds do not respect service locale

### ISSUE THREAD

**Issue by jasonmit** [stefanpenner/ember-moment#135]
Computed macros do not respect the service's locale, but that's probably not something we can easily solve unless we decide to inject moment into all common factory types.

What we can do, and probably should do, is support some way of specifying a locale.  Below are two proposals.

```js
format('createdOn', 'MM/DD/YYYY', {
  locale: 'moment.locale'
})
```

Or support computed composition

```js
locale(moment('createdOn'), 'moment.locale')
```

**Comment by jasonmit** [comment]
@stefanpenner I'm leaning towards the composition approach since it's more flexible and condusive to supporting the entire moment API if we take it further:

`locale(format(moment('createdOn'), 'MM/DD/YYYY'), 'moment.locale')`

**Comment by stefanpenner** [comment]
> locale(format(moment('createdOn'), 'MM/DD/YYYY'), 'moment.locale')

isn't the format also locale specific?

**Comment by stefanpenner** [comment]
> diff(moment('createdOn'), new Date())
> 
> fromNow(moment('createdOn'))
> 
> toNow(moment('createdOn'))
> 
> duration(10, 'hours')

this looks good, but seems orthogonal to the locale issue right?

**Comment by stefanpenner** [comment]
> Computed macros do not respect the service's locale, but that's probably not something we can easily solve unless we decide to inject moment into all common factory types.

I'm kinda fine with that, but likely only if the thing injected is unlikely to collide with peoples existing properties.

**Comment by jasonmit** [comment]
Yes bad example with the use of format.  You would use format with locale

**Comment by jasonmit** [comment]
> this looks good, but seems orthogonal to the locale issue right?

Not really, since we would be adding locale support to all those computeds by fixing this issue, which means adding a tail argument  or supporting an options hash.  The more I thought about it, the more it makes sense to just mimic the chaining behavior of moment API with our computeds.

```js
locale(fromNow(moment('createdOn')), 'moment.locale')
locale(toNow(moment('createdOn')), 'moment.locale')
locale(duration(10, 'hours'), 'moment.locale')
```

or

```js
format('createdOn', 'moment.locale')
fromNow('createdOn', 'moment.locale')
toNow('createdOn', 'moment.locale')
duration(10, 'hours', 'moment.locale')
```

The above approach is more or less what we have today, minus the tail argument for locale.  It's problematic though since there are arguments in between moment and the locale that would need to be explicitly passed.  So the above would really look like:

```js
format('createdOn', 'MM/DD/YYYY', 'LLLL', 'moment.locale')
fromNow('createdOn', false, 'moment.locale')
toNow('createdOn', false, 'moment.locale')
duration(10, 'hours', 'moment.locale')
```
