### ISSUE TITLE
Cannot run with moment 2.11

### ISSUE THREAD

**Issue by gzurbach** [stefanpenner/ember-moment#140]
Moment 2.11 was released two days ago: https://github.com/moment/moment/releases/tag/2.11.0

This morning our Jenkins test suite failed with the following error: `ReferenceError: Can't find variable: module`.

It's a runtime error thrown during acceptance tests.

After looking at the `bower.json` I noticed that `ember-moment` specifies `"moment": ">= 2.8.0"`. This is the reason why our Jenkins installed 2.11 and produced a bad build.

After locking moment to 2.10.6 (`"moment": "2.10.6"`), everything works again.

**Comment by jasonmit** [comment]
Likely caused by the shape of the npm package changing.

**Comment by jasonmit** [comment]
@gzurbach temporarily going to lock moment to `>= 2.8.0 < 2.11.0` until I find the time to fix.

**Comment by stefanpenner** [comment]
@jasonmit i believe moment just wants to be compiled via babel or similar.

**Comment by jasonmit** [comment]
> Although they likely also package a pre-built version, maybe just not at the location we expect?

That's like it since we don't do any building, we just consume the disted bower package(s) and pluck the locales your application needs versus using the full dist.

**Comment by stefanpenner** [comment]
@jasonmit strange that they would change that without bumping a major version..

**Comment by gzurbach** [comment]
@jasonmit Thanks for getting on this so quickly. Really appreciate the reactivity!

**Comment by jasonmit** [comment]
@stefanpenner tell me about it, it happened pre-2.8.0 as well.

**Comment by jasonmit** [comment]
@gzurbach can you paste your `config/environment.js`

**Comment by jasonmit** [comment]
This appears to be a bug in momentjs as of 2.11.0 https://github.com/moment/moment/issues/2862

Aside from this bug, it doesn't look to be incompatible with ember-moment so I'll remove the lock down once they patch 2.11.0

**Comment by jasonmit** [comment]
This should now be resolved since 2.11.1 was released.
