### ISSUE TITLE
Interval not working

### ISSUE THREAD

**Issue by cdnrg** [stefanpenner/ember-moment#146]
I'm not sure if interval is only meant to work with "moment-from-now". I am trying to use this for a simple clock but it is not updating:

`{{moment-format date 'h:ma' interval=1000}}`

New to Ember so let me know if I am making an obvious mistake! Appreciate the help.

Edit - Looking at the source, I see that moment-format.js does not include the check for interval. Would be great to have this feature.

**Comment by jasonmit** [comment]
I am all for this feature request if you wanted to spike a PR

**Comment by cdnrg** [comment]
#147 Hopefully that will do the trick. Just based it on moment-from-now.

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/pull/151
