### ISSUE TITLE
Ember-CLI test

### ISSUE THREAD

**Issue by andorov** [stefanpenner/ember-moment#15]
I have a component that uses `ago` in its template.  No problem compiling the template in development, but how do you include it in the test?  I've tried various ways with no success.

```
<Ember._HandlebarsBoundView:ember300> Handlebars error: Could not find property 'ago' on object <(subclass of Ember.Component):ember298>.
```

**Comment by jrjohnson** [comment]
Is adding this to every component unit test the only way to make them work?  I don't understand enough about the way each test is executed so my attempts to add the initializer to startApp were un-successful, but that would seem like a better strategy.

**Comment by mgenev** [comment]
is this really resolved? using this addon is breaking my tests right now, see here:
http://stackoverflow.com/questions/29475291/installing-an-ember-helper-through-add-on-then-using-it-in-a-component-breaks-th
