### ISSUE TITLE
{{moment-calendar ...}} not found

### ISSUE THREAD

**Issue by badazz91** [stefanpenner/ember-moment#150]
Using the ``` {{moment-calendar}}``` helper triggers following error:

```Uncaught Error: Assertion Failed: A helper named 'moment-calendar' could not be found```.

 I'm using  ```"ember-moment": "4.1.0"```.

**Comment by jasonmit** [comment]
@badazz91 moment-calendar landed in 5.1.0

**Comment by badazz91** [comment]
Sry my bad. Updated to the latest ember-moment. Now it works... 

But the latest tag on this project is still 4.1.0. Isn't this odd?
