### ISSUE TITLE
How do you ignore prefix/suffix?

### ISSUE THREAD

**Issue by djsegal** [stefanpenner/ember-moment#152]
In my hbs file, I have:

`{{moment-from-now post.created_at}}`

I was wondering how you ignore the `ago` that gets added. It seems like #137 fixed something similar.

**Comment by jasonmit** [comment]
`{{moment-from-now post.created_at hidePrefix=true}}` should do it

**Comment by djsegal** [comment]
@jasonmit `hideSuffix` in this case, but thank you!

**Comment by jasonmit** [comment]
:+1: err, yes
