### ISSUE TITLE
Allow empty set and still see invalid date

### ISSUE THREAD

**Issue by Jordan4jc** [stefanpenner/ember-moment#154]
I have a date coming in as `YYYY-MM-DD` but sometimes this is set to `0000-00-00` from my backend, I have defined my `moment-format` as such

    {{moment-format model.event_date "D MMM YYYY" "YYYY-MM-DD" allow-empty=true}}

But I still see `Invalid Date` in the template

**Comment by jasonmit** [comment]
0000-00-00 is not empty

**Comment by Jordan4jc** [comment]
Is there a way to not show invalid date and just not render?

**Comment by jasonmit** [comment]
Not currently, but I am not opposed to adding it.

**Comment by Jordan4jc** [comment]
That would be helpful, I suppose I can add a computed to my model that returns true if the date is `0000-00-00` but that seems counter intuitive to write a computed just to not show a date, maybe not though.
