### ISSUE TITLE
Will helper update model with changed value

### ISSUE THREAD

**Issue by jrock2004** [stefanpenner/ember-moment#159]
Using your plugin and its pretty cool. The problem I have is when I change the date, the model value does not update. If I do not use your plugin, I do not have this issue. Thoughts?

```
{{input value=(moment-format model.datetime "MM/DD/YYYY hh:mm A")}}
```

**Comment by jasonmit** [comment]
This is an invalid use, and not a bug with ember-moment.  What you're doing is binding the output of moment-format (a string literal) to an input.  Changing the input isn't changing your model attribute but instead just a string literal.

You likely want to do something using data-down/actions-up where you display a formatted value but editing the input changes the display value.
