### ISSUE TITLE
Ember 2.4 environment.js

### ISSUE THREAD

**Issue by jrock2004** [stefanpenner/ember-moment#160]
I am trying to set the default format for moment but looking at documentation I am not sure where to put the code. I thought maybe it would go in ENV object but that did not work.  Here is what my env file looks like

```
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'thunder',
    environment: environment,
    contentSecurityPolicy: { 'connect-src': "'self' https://auth.firebase.com wss://*.firebaseio.com" },
    firebase: 'https://coolio-app.firebaseio.com/',
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },

    moment: {
      outputFormat: 'MM/DD'
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};
```

I then created a transformer

```
import DS from 'ember-data';
import moment from 'moment';
​
export default DS.Transform.extend({
  deserialize(serialized) {
    console.log(moment.defaultFormat);
    return moment(serialized).format();
  },
​
  serialize(deserialized) {
    return new Date(deserialized);
    // return deserialized;
  }
});
```

The log does not show the new format. What I am doing wrong here

**Comment by stefanpenner** [comment]
the docs show `// config/environment.js`

**Comment by jrock2004** [comment]
That is from the config/environment.js

**Comment by jasonmit** [comment]
@jrock2004 the default `outputFormat` is used when invoke the format helper or computed property.  We do not close over moment functions and implement our own logic.

Helper example: https://github.com/stefanpenner/ember-moment/blob/6e17cb6f5136b4914aca6c1a7ad0629b7d5696b3/tests/unit/helpers/moment-format-test.js#L27-L49

**Comment by jonathansamines** [comment]
I´m just having the same problem with ember@2.4. The default outputFormat configuration doesn´t seems to be affecting the usage of `ember-format` helper.

**Comment by jasonmit** [comment]
Reopened to investigate and at the very least will submit a PR to add test coverage here.

**Comment by jasonmit** [comment]
Is this still an issue?  Feel free to reopen.

**Comment by Panman8201** [comment]
Yeah, for some reason I cannot get any options in `config/environment.js` to take effect. I'm trying to set both `allowEmpty` and `outputFormat`. I'm on version 2.7 of ember/ember-cli and 7.0.0-beta.3 of ember-moment.
