### ISSUE TITLE
You should be able to format a date to ISO 8601

### ISSUE THREAD

**Issue by zacstewart** [stefanpenner/ember-moment#161]
Moment does this by default if you don't specify a format when calling `moment().format()`. Looks like this plugin insists on a default format instead of letting me explicitly say "no format, just give me ISO 8601."

**Comment by jasonmit** [comment]
This is through the moment-format helper?

**Comment by zacstewart** [comment]
Sorry, I wasn't clear. Yes. I expected `moment-format myDate` to be ISO 8601.
