### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by jasonmit** [stefanpenner/ember-moment#164]
`ember-release` matrix failing because of `ember-template-compiler`

`TypeError: Object.keys called on non-object`

https://travis-ci.org/stefanpenner/ember-moment/jobs/122278886

**Comment by jasonmit** [comment]
Fix will require using momentForComponent and removing legacy views in the test suite.

Similar to this PR: https://github.com/jasonmit/ember-intl/pull/326

**Comment by stefanpenner** [comment]
@rwjblue c/d?

**Comment by rwjblue** [comment]
`moduleForComponent` is the right way to go for testing helpers at the moment, but the specific error in that Travis job linked above was related to a bug I introduced and has been fixed in https://github.com/emberjs/ember.js/pull/13299.

**Comment by stefanpenner** [comment]
thanks @rwjblue
