### ISSUE TITLE
Support for Moment Addons?

### ISSUE THREAD

**Issue by toobulkeh** [stefanpenner/ember-moment#165]
We'd like to use a [moment-duration-format](https://github.com/jsmreese/moment-duration-format) addon to customize the output of a duration string.

It would be a time saver if this project supported it.

There's [a large discussion](https://github.com/moment/moment/issues/463) on why this isn't incorporated into moment.js with 90x 👍  over the past 5 years.

Doing this manually would require some kind of [clock implementation](http://livsey.org/blog/2013/02/20/tick-tock/) that is a road we really don't want to go down.

Has a concept like this been brought up before, that my searches missed; or does it sound like a bad idea for a reason I probably don't understand?

**Comment by jasonmit** [comment]
I'd like to keep the features limited to what moment supports and and additional features can be supported with additional addons that extend ember-moment's functionality.

I'll leave the issue opened though for further discussion.
