### ISSUE TITLE
converting UTC

### ISSUE THREAD

**Issue by haldiggs** [stefanpenner/ember-moment#167]
how would I take my GMT date and convert it to my local timezone?

given 
gmtDate="Fri Apr 15 2016 06:21:52 GMT-0500 (Central Daylight Time)"
this usually does it
moment.utc(gmtDate).format("MM/DD/YYYY hh:mm:ss a")

I have enabled the timezone part but just didn't quite see the example that might help me out.

**Comment by jasonmit** [comment]
http://momentjs.com/timezone/
