### ISSUE TITLE
moment-timezone not available.

### ISSUE THREAD

**Issue by angelosarto** [stefanpenner/ember-moment#171]
I am seeing this message when I try to set the timezone.
[ember-moment] attempted to set timezone, but moment-timezone unavailable.

I installed using ember install ember-moment and I added to the config/environment.js:
In package.json I do see ember-moment and the shim but I don't see timezone.  
However if I look in bower.json I don't see moment listed at all.

Did I somehow mess up the install?   The helpers work as long as I don't try to set the timezone.

environment.js
`moment: {
      // Options:
      // 'all' - all years, all timezones
      // '2010-2020' - 2010-2020, all timezones
      // 'none' - no data, just timezone API
      includeTimezone: 'all',
      includeLocales: true
    }`

bower.json
`{
  "name": "user-app",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.1.0",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": ">= 1.7.0 < 2.2.0",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "spin.js": "~2.3.2",
    "foundation-sites": "~6.1.1",
    "foundation-icon-fonts": "*",
    "zxcvbn": "~4.0.1",
    "pretender": "~0.12.0",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "tether": "^1.0.3",
    "file-saver.js": "~1.20150507.2",
    "auth0-lock": "^7.10.2",
    "jsrsasign": "^5.0.1",
    "pikaday": "~1.4.0"
  },
  "resolutions": {
    "ember": "v2.3.0"
  }
}
`

package.json
`
"devDependencies": {
    "auth0-ember-simple-auth": "git://github.com/auth0/auth0-ember-simple-auth.git#ffc5ebf9de6b813cb36f958e6e80d1494bf2f627",
    "broccoli-asset-rev": "^2.1.2",
    "broccoli-funnel": "^1.0.1",
    "broccoli-unwatched-tree": "^0.1.1",
    "ember-ajax": "0.7.1",
    "ember-cli": "1.13.8",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-content-security-policy": "0.5.0",
    "ember-cli-cookie": "^0.2.0",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-deploy": "0.5.0",
    "ember-cli-deploy-lightning-pack": "0.2.0",
    "ember-cli-dotenv": "1.0.4",
    "ember-cli-focus-input": "^1.0.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-mirage": "^0.2.0-beta.8",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-password-strength": "0.1.1",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.3",
    "ember-cli-sass": "5.2.1",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.3.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-link-action": "0.0.34",
    "ember-modal-dialog": "0.8.3",
    "ember-moment": "6.1.0",
    "ember-pikaday": "1.1.0",
    "ember-power-select": "0.10.1",
    "ember-simple-auth": "1.1.0-beta.3",
    "ember-spin-spinner": "0.2.4",
    "ember-tether": "0.2.1",
    "ember-validations": "~2.0.0-alpha.4",
    "emberx-select": "2.0.2",
    "sync-exec": "^0.6.2"
  },`

**Comment by jasonmit** [comment]
moment and moment-timezone and npm deps in this case, not bower deps.

Running `ember g ember-cli-moment-shim` should resolve this.

**Comment by jasonmit** [comment]
Reopening since that still doesn't solve your question, but answers your bowser concern.

**Comment by jasonmit** [comment]
Can you try and reproduce it in isolate and push that project to github so I can inspect.  I cannot reproduce this locally.

**Comment by angelosarto** [comment]
ember g ember-cli-moment-shim
 
did seem to the do the trick!  Thanks

**Comment by jasonmit** [comment]
It sounds like you are on an older version of the shim.  I suspect it is pikaday.  Can you run npm ls ember-cli-moment-shim and less me what that outputs.

**Comment by angelosarto** [comment]
I am not sure which I had in first, but I didn't add the pikaday change to ember-cli-build.js:

user-app@ /Users/angelosarto/Work/user-app
`-- ember-cli-moment-shim@1.1.0

**Comment by devinrhode2** [comment]
The error above is caused by just installing ember-auto-import ^1.2.13 with moment ^2.17.1, ember-cli-moment-shim ^3.5.0, and ember-moment": ^7.3.0.

**Comment by devinrhode2** [comment]
Linking to some discussions about this...
Looks like this is first discussion where the issue first appeared, opened by @urbany "Import conflict when using in a project along-side ember-auto-import" https://github.com/cibernox/ember-power-calendar/issues/164

A potential solution from @urbany (testing this now) "How to not bundle all moment locales" https://github.com/ef4/ember-auto-import/issues/114#issuecomment-415701712

Last but not least a discussion+code about how to solve this long term also by @urbany "WIP: Use ember-auto-import" https://github.com/jasonmit/ember-cli-moment-shim/pull/168

@ef4 could you recommend an ember-cli-build.js config for `autoImport` that'd solve this issue with moment-timezone not getting imported properly?

**Comment by stfnio** [comment]
@devinrhode2 if I understood correctly, all we have now is to wait until moment-for-ember authors come up with some decision regarding this problem? Thanks for the clarification in your post btw!

**Comment by devinrhode2** [comment]
I am not really sure tbh. Not working with ember or the same team anymore either.

**Comment by jasonmit** [comment]
We'll end up swapping ember-cli-moment-shim over to internally use ember-auto-import while also deprecating it the addon.

For those who are conscious of bundle size and only want certain locales/timezone builds, we'll address that with [documentation](https://github.com/ef4/ember-auto-import/issues/114#issuecomment-415647939).

PRs obviously welcome to move it along.
