### ISSUE TITLE
Localication is not working

### ISSUE THREAD

**Issue by choallin** [stefanpenner/ember-moment#173]
I want to set the local option gloably in my app/routes/inventorie,js like this:
```javascript
export default Ember.Route.extend({  
  moment: Ember.inject.service(),  
   beforeModel() {  
    this.get('moment').changeLocale('fr');  
    console.log(this.get('moment'));  
  },  
  model() {  
    return this.store.findAll('inventory');  
  }  
});
```
In the console I see now that the local is set to "fr", but the date is not formatted right.  
Here is the hbs:
```
   {{#md-table-col row=row header='Installationsdatum' key='dateOfOrder'}}
    {{moment-format row.dateOfOrder}}
  {{/md-table-col}}
  {{#md-table-col row=row header='Garantie bis' key='warrantyUntil'}}
    {{moment-from-now row.warrantyUntil 'M' locale='de'}}
  {{/md-table-col}}
```
Did I do something wrong or is this not working?  
(I'm using Ember 2.5.1 and installed ember-moment with ember install ember-moment a few hours ago)

**Comment by stefanpenner** [comment]
if possible can you provide a repo demonstrating this issue, it would make it much easier to debug

**Comment by jasonmit** [comment]
Are you sure you configured ember-moment to bring in the locale data for `fr`?

https://github.com/stefanpenner/ember-moment#i18n-support

**Comment by choallin** [comment]
In my environment.js I have done this to get the locals:
```javascript
moment: {
      includeLocales: ['de-at','de', 'fr'],
      outputFormat: 'L'
    }
```
Do I have any way to check if the locales are loaded?

**Comment by jasonmit** [comment]
`moment.locale()` will return the locale that is active. `moment.locales()` gives you a list of all the locales that have been loaded.

Please put together an example reproducing the issue.

**Comment by choallin** [comment]
You can close this issue.  
I restarted the ember server and now I get the right local...
