### ISSUE TITLE
Introduction to ember-moment on The Ember Show at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [stefanpenner/ember-moment#174]
Would you someone familiar with this library be interested in giving a lightning talk about this addon on The Ember Show? We're recording the next episode on June 11th followed by July 2nd. 

An introduction to <addon> talk is about 15 minutes long and covers the following:
- Why was this addon created?
- When should it be used?
- How does one get started?
- What should the person be aware of?

You can see some of the previously recorded introduction talks on [Global Ember Meetup Videos](https://www.embermeetup.com/videos?category=addon-introductions) page.

Would you be able to give this talk?

**Comment by jasonmit** [comment]
Closing since the event is in the past
