### ISSUE TITLE
Support for ember-calendar format customisation

### ISSUE THREAD

**Issue by steffenbrem** [stefanpenner/ember-moment#176]
I don't seem to find a proper way to allow the `ember-calendar` helper to apply custom formatting (as described in the docs: http://momentjs.com/docs/#/displaying/calendar-time/). 

Would a syntax like `{{moment-calendar date sameElse="DD/MM/YYYY HH:mm"}}` be acceptable?

**Comment by jasonmit** [comment]
> Would a syntax like {{moment-calendar date sameElse="DD/MM/YYYY HH:mm"}} be acceptable?

:+1:

**Comment by samselikoff** [comment]
In the meantime, is there a way to update global configuration? I tried

```js
// application/route.js
import Ember from 'ember';
import moment from 'moment';

export default Ember.Route.extend({

  beforeModel() {
    moment.updateLocale('en', {
      sameDay: '[Today]',
      nextDay: '[Tomorrow]',
      nextWeek: 'dddd',
      lastDay: '[Yesterday]',
      lastWeek: '[Last] dddd',
      sameElse: 'MMM, YYYY [at] h:mm a'
    });
});
```

to no avail.

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/pull/179 should close this out.

You can now pass the format values as attributes (lastDay and sameDay in the example below):

```hbs
{{moment-calendar date referenceDate lastDay='[Yesterday]' sameDay='[Today!]'}}
```

You can also pass a full format object as the third argument:

```js
  this.setProperties({
    date: moment('2013-01-01T02:30:26Z'),
    referenceDate: moment('2013-01-01T12:00:00Z'),
    formats:  {
      sameDay: '[Today]',
      nextDay: '[Tomorrow]',
      nextWeek: 'dddd',
      lastDay: '[Yesterday]',
      lastWeek: '[Last] dddd',
      sameElse: 'DD/MM/YYYY'
    }
  });

  this.render(hbs`{{moment-calendar date referenceDate formats}}`);
```

**Comment by ixSci** [comment]
I can't set it application wide, can I?

**Comment by jasonmit** [comment]
@ixSci no but I would be open to review a PR that sets formats on the service and the helpers/cps will check there if not passed as an attr.
