### ISSUE TITLE
Moment helpers timeZone not working?

### ISSUE THREAD

**Issue by naelkhann** [stefanpenner/ember-moment#180]
Hey,

I'm using ember v.2.5.0 and I'm trying to use ember-moment to beautifully include dates and times. Here are some vague photos of my project. Basically, it seems as though no matter what I change the timeZone value too, the time displayed does not change. It just stays at my standard time (in NY). What's the issue? The second image is how my times are displaying (all different timezones yet showing the same time). First is handlebars helper code.

![screen shot 2016-06-22 at 4 28 19 pm](https://cloud.githubusercontent.com/assets/12739780/16282341/5e3fc266-3896-11e6-83b0-42d7ca0c2eab.png)
![screen shot 2016-06-22 at 4 25 13 pm](https://cloud.githubusercontent.com/assets/12739780/16282340/5e3f358a-3896-11e6-97d7-54d9ef84e8ee.png)

**Comment by jasonmit** [comment]
Usually, this happens when you have another addon which might app.import moment.

Can you list out all your addons that your project uses?
