### ISSUE TITLE
Using UTC

### ISSUE THREAD

**Issue by JeroenvdV** [stefanpenner/ember-moment#182]
Hi, 

I'm using this as follows:

`{{moment-calendar drawing.updated_at locale='nl'}}`

However, drawing.updated_at is a UTC time string. It is displayed as the UTC time, but I would like it to be displayed in the user's time zone. How can I tell moment that the input time is UTC rather than local time, so that it is converted? From the moment docs it seems that it is possible to call moment.utc() for this. Is this implemented in ember-moment or is there a work-around?

**Comment by jasonmit** [comment]
Something like the follow may work.

```js
// app/helpers/moment-utc.js
import moment from 'moment';

export default Ember.Helper.helper(function([time]) {
  return moment.utc(time);
});
```

```hbs
{{moment-calendar (moment-utc drawing.updated_at) locale='nl'}}
```

**Comment by jasonmit** [comment]
Reopen if this doesn't address your question.

**Comment by JeroenvdV** [comment]
Thanks, this works with:   `return moment.utc(time).local();`

**Comment by toobulkeh** [comment]
It would be nice if this was a default, or configurable option. The helper with `local()` seems verbose for a common use case (displaying times in the local timezone).

**Comment by jasonmit** [comment]
Feel free to propose an API that you think would make it easier.  Happy to implement it.

**Comment by toobulkeh** [comment]
`{{moment-format-local time}}`

**Comment by jasonmit** [comment]
I wouldn't want to combine the helpers like that.  But there is nothing stopping you from adding this helper within your own project if it's useful and saves typing over composition:

`{{moment-format (local (utc dateTime))}}` I would prefer this.
