### ISSUE TITLE
Yesterday  === 2 days ago

### ISSUE THREAD

**Issue by gordonbisnor** [stefanpenner/ember-moment#183]
I've noticed an issue using moment-from-now where I am setting a date in an Ember Data model field with attr('string') type set  to yesterday (eg 2016-08-01), and it displays as 2 days ago. 

I see that an [issue was opened in moment.js](https://github.com/moment/moment/issues/3246) where anything over 24 hours is considered 2 days ago. In my case I'm looking at a date only, but moment must be converting my date string to datetime. 

Don't know if this is outside the scope of ember-moment, and perhaps in the domain of moment.js. Strikes me that when a date only is passed, such as 2016-08-01, ideally it would show as 1 day ago or Yesteday for the duration of 2016-08-02.

**Comment by gordonbisnor** [comment]
I found a workaround for this for my own project, eg:

**template:**

```handlebars
{{#if today}}
  today
{{else if yesterday}}
  yesterday
{{else}}
  {{moment-from-now entry.date}}
{{/if}}
```

**component:**

```javascript
import Ember from 'ember';
import moment from 'moment';

export default Ember.Component.extend({
	today: Ember.computed('entry.date', function () {
		let date = this.get('entry.date');
		return moment(date).isSame(moment(), 'day');
	}),
	yesterday:  Ember.computed('entry.date', function () {
		let date = this.get('entry.date');
		let yesterday = moment().subtract(1, 'days'); // 07/23/2016
		return moment(date).isSame(yesterday, 'day');
	}),

});
```

**Comment by jasonmit** [comment]
I'd prefer not to deviate from moment's builtin functionality.  That would lead us down a slippery slope.  If the incorrect parsing to datetime is within ember-moment, I'd be happy to fix.

**Comment by gordonbisnor** [comment]
That makes sense. In this case ember-moment is calling moment() on the field, eg "2016-08-01" and then fromNow. So ember-moment is probably doing exactly what it should do in terms of wrapping moment. 

On moment's end it might be nice if there was an option to specify within fromNow that the accuracy need only be in days, or as the poster of the moment issue pointed out, an option to not round to 2 days immediately after 24 hours. But as you point out that's nothing to do with ember-moment.

**Comment by gordonbisnor** [comment]
What I ended up with here was something more like this, where I realized that I needed to use from/to rather than fromNow/toNow, and then used moment() as a starting point, but formatted to  YYYY-MM-DD to zero out the times to match my date fields, and then compare from there.

```javascript
import Ember from 'ember';
import moment from 'moment';
export default Ember.Mixin.create({
	daysToNowFrom(date) {
		const now = moment().format('YYYY-MM-DD');
		const then = moment(date).format('YYYY-MM-DD');
		if (moment(date).isSame(moment(), 'day')) {
			return 'today';
		} else if (moment(date).isSame(moment().subtract(1, 'days'), 'day')) {
	  	return 'yesterday';
		} else {
			return moment(now).to(then);	
		}
	}
});
```
