### ISSUE TITLE
Setters for computeds?

### ISSUE THREAD

**Issue by davewasmer** [stefanpenner/ember-moment#184]
It would be nice to have computed macros that supply getters and setters, at least for the `format` macro.

Our use case is for serializing / deserializing dates in query params. We want easily formatted query param values like `?start=2016-08-10`, but want moment objects to work with in the code, so we end up with:

``` js
const DATE_FORMAT = 'YYYY-MM-DD';

export default Ember.Controller.extend({
  queryParams: [ 'start' ],
  start: moment().format(DATE_FORMAT),
  startDate: computed('start', {
    get() {
      return moment(this.get('start'), DATE_FORMAT);
    },
    set(key, value) {
      this.set('start', value.format(DATE_FORMAT));
      return value;
    }
  })
});
```

It would be nice if we could just do something like:

``` js
const DATE_FORMAT = 'YYYY-MM-DD';

export default Ember.Controller.extend({
  queryParams: [ 'start' ],
  start: moment().format(DATE_FORMAT),
  startDate: momentAlias('start', DATE_FORMAT)
});
```

You could even name them similar to the built-in macros, i.e. `momentAlias` would support get/set, and `momentRead` would be read only.

Happy to take a stab at a PR, but wanted to validate the concept first.

**Comment by jasonmit** [comment]
I agree with the general approach.  I think we should aim to implement this setter across all the computed.  If the last argument is a function, use it as the setter.

```js
{
  formattedDate: format('date', 'MM/DD', function(dateValue) {
    /* the setter */
  })
}
```

**Comment by davewasmer** [comment]
@jasonmit just curious - why make the user provide the setter? At least in the case of `format`, the expected behavior seems pretty obvious (it should read in a string of the same format, and set the underlying aliased property to the parsed value of that string). Are there some edge cases I'm missing perhaps?

**Comment by jasonmit** [comment]
@davewasmer setter support across all the CP macro.  And it's possible/likely people may want to implement custom setter behavior on moment-format, such as setting another property or assertions.

**Comment by jasonmit** [comment]
We're moving towards implementing readOnly #214.
