### ISSUE TITLE
Can't use other locales, always uses english

### ISSUE THREAD

**Issue by ptraceur** [stefanpenner/ember-moment#185]
Hi,
I wanted to use another locales so I've tried all the ways I could find on the documentation, but the results were only given in english.

I've tried to define a default locale with the following code:
(this is the only code I have in my application.js route file)
```js
import Ember from 'ember';
import moment from 'moment';

export default Ember.Route.extend({
	beforeModel() {
		moment.locale('pt');
	}
});
```

And this:
```html
{{moment-from-now my_date locale="pt"}}
```

And I'm getting this warning in the js console, although I don't think this is related, but here it is:
```
ember-moment: an empty value (null, undefined, or "") was passed to moment-format
```

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment#globally-set-locale is how you change the locale

**Comment by ptraceur** [comment]
This is my code now, still getting results in english

```
import Ember from 'ember';
import config from '../config/environment';

export default Ember.Route.extend({
	moment: Ember.inject.service(),
	beforeModel() {
		this.get('moment').changeLocale('fr');
	}
});
```

**Comment by jasonmit** [comment]
Push an example app with the issue isolated to github.

**Comment by chamoysvoice** [comment]
I have the same problem @ptraceur, did you solve it?

**Comment by jasonmit** [comment]
The easiest/quickest way for me to solve these is if I can reproduce it, so if you can throw together a quick dummy app with the bug I can take a look.  FYI, most of the time I've encountered this issue is when another addon also app.imports moment and there for momentjs gets bundled twice.

**Comment by jasonmit** [comment]
Also,  @chamoysvoice and @ptraceur be sure to read https://github.com/stefanpenner/ember-moment#cherry-pick-locales-optimal if you already haven't since you did not mention adding the locales to `config/environment`.

**Comment by xomaczar** [comment]
Having the same problem, everything works if I build production version, in dev I only see en locale

**Comment by jasonmit** [comment]
@xomaczar likely one of your dependencies is including moment.

Also see https://github.com/stefanpenner/ember-moment/issues/132

**Comment by xomaczar** [comment]
Can we add some verbiage to README.md?

**Comment by jasonmit** [comment]
I'd happily review any PR around this since it seems to continue to surface.
