### ISSUE TITLE
shows "Invalid date" in safari (desktop, mobile)

### ISSUE THREAD

**Issue by ihomp** [stefanpenner/ember-moment#187]
shows "Invalid date" in safari (desktop, mobile)

**Comment by jasonmit** [comment]
I need more information.

**Comment by ihomp** [comment]
Does it work for anyone in safari ?

**Comment by ihomp** [comment]
Ember 2.1.0

```
  "devDependencies": {
    "awesome-phonenumber": "^1.1.1",
    "broccoli-asset-rev": "^2.4.6",
    "ember-body-class": "0.3.8",
    "ember-browserify": "1.1.9",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.5.0",
    "ember-cli-babel": "^5.1.9",
    "ember-cli-content-security-policy": "0.5.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-dotenv": "1.0.4",
    "ember-cli-emblem": "0.3.1",
    "ember-cli-facebook-js-sdk": "0.0.4",
    "ember-cli-google-analytics": "^1.5.0",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-intercom": "0.4.0",
    "ember-cli-mirage": "0.1.9",
    "ember-cli-moment-shim": "2.1.0",
    "ember-cli-password-strength": "0.1.1",
    "ember-cli-qunit": "^1.4.2",
    "ember-cli-release": "0.2.3",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-stylus": "1.0.5",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-zero-clipboard": "1.1.1",
    "ember-click-outside": "0.0.3",
    "ember-component-css": "0.1.6",
    "ember-data": "2.8.0",
    "ember-data-url-templates": "0.1.1",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-i18n": "4.2.2",
    "ember-i18n-inject": "0.0.2",
    "ember-infinity": "0.2.2",
    "ember-inflector": "1.9.6",
    "ember-link-action": "0.0.34",
    "ember-moment": "6.1.0",
    "ember-radio-buttons": "4.0.1",
    "ember-select-list": "0.9.3",
    "ember-truth-helpers": "1.2.0",
    "ember-websockets": "1.2.4",
    "formidable": "1.0.17",
    "liquid-fire": "0.21.3",
    "querystring": "0.2.0",
  }
```

**Comment by jasonmit** [comment]
I ran the dummy app against 6.1.0 with Safari and I'm not seeing this.

Which method are you invoking and what is being passed to that method?

**Comment by ihomp** [comment]
`{{moment-from-now item.bookingDate interval=1000}}`

**Comment by jasonmit** [comment]
What is the value of bookingDate?

**Comment by ihomp** [comment]
'2016-05-30T09:12:48+0200'

**Comment by jasonmit** [comment]
<img width="872" alt="screen shot 2016-09-21 at 9 32 05 am" src="https://cloud.githubusercontent.com/assets/3108309/18719926/4d6612ee-7fde-11e6-94b7-7b06e97497ac.png">


I cannot reproduce this, please through together an example app because there is likely something else going on in your app code.

**Comment by ihomp** [comment]
in 4 month? 30th of may 2016

**Comment by jasonmit** [comment]
```
moment('2016-05-30T09:12:48+0200').fromNow()
"4 months ago"
```

**Comment by jasonmit** [comment]
If you were expecting, "A few seconds ago"

`{{moment-from-now (now) '2016-05-30T09:12:48+0200' interval=1000}}`

**Comment by ihomp** [comment]
{{moment-format '2016-05-30T09:12:48+0200' 'llll'}}

also works perfectly for me in Chrome and Firefox, but not in safari (tried both mobile and on pc). 
safari return "Invalid date".

**Comment by ihomp** [comment]
@jasonmit any ideas what I should check.. 
what version of safari do you use? 

I use Version 10.0 (10602.1.50.0.10)

**Comment by jasonmit** [comment]
Was tested on 9.1.2

**Comment by jasonmit** [comment]
Do you also get Invalid Date if you invoke this directly:

`moment('2016-05-30T09:12:48+0200').format('llll')`

**Comment by ihomp** [comment]
trying now..

**Comment by jasonmit** [comment]
Can you also run this command and paste the output:
`npm ls moment moment-timezone`

**Comment by ihomp** [comment]
WOW! it works like: **moment('2016-05-30T09:12:48+0200').format('llll')**

great...

**Comment by ihomp** [comment]
├─┬ ember-cli-moment-shim@2.1.0
│ ├── moment@2.15.1 
│ └── moment-timezone@0.5.5 
└─┬ ember-cli-release@0.2.3
  └─┬ moment-timezone@0.3.1 
    └── moment@2.14.1

**Comment by jasonmit** [comment]
Can you also try `{{moment-format '2016-05-30T09:12:48+0200' 'llll'}}` as string literals instead of referencing `item.bookingDate`

**Comment by ihomp** [comment]
also works, Mon, May 30, 2016 9:12 AM

**Comment by jasonmit** [comment]
And finally, try this: `{{moment-format item.bookingDate 'llll' allow-empty=true}}`

**Comment by ihomp** [comment]
that's doesn't work..

**Comment by jasonmit** [comment]
Are you sure `item.bookingDate` is a string the moment that it renders?  That definitely feels like what is happening here.

You can validate this using the debugger helper: https://guides.emberjs.com/v1.10.0/templates/development-helpers/

**Comment by ihomp** [comment]
Thanks alot, I found what was the problem..
I had in my model:

` bookingDate: DS.attr('date'),`

chnaged to

` bookingDate: DS.attr('string'),`

now works..

`{{log 'date: ' item.bookingDate}}`


**chrome:** 

`date:  Mon May 30 2016 09:02:48 GMT+0200 (CEST)`

**FireFox**

`date:  Date 2016-05-30T07:02:48.000Z`

**Safari**

`date:  – Invalid Date `

**Comment by jasonmit** [comment]
Thanks for reporting back, will likely be useful for future travelers!
