### ISSUE TITLE
Support for unix timestamp conversion

### ISSUE THREAD

**Issue by stavarotti** [stefanpenner/ember-moment#189]
I often find myself doing the following:

```js
@computed('model')
createdAt() {
  return moment.unix(this.get('model.time'));
}
```

And then

```hbs
{{moment-from-now createdAt}}
```

Adding a `unix` helper would be beneficial and remove the need to have the computed.  Perhaps something like so:

```hbs
{{moment-from-now (unix model.time)}}
```

Does this sound useful?  If so, I can have a PR ready shortly.

**Comment by jasonmit** [comment]
I am very much in favor :)

**Comment by jasonmit** [comment]
Thanks again @stavarotti

**Comment by stavarotti** [comment]
@jasonmit absolutely.
