### ISSUE TITLE
Could we keep the beta of ember-moment out of "latest" on npm?

### ISSUE THREAD

**Issue by kitsunde** [stefanpenner/ember-moment#192]
Hello!

ember-moment seems to publish beta releases to npm under latest:

```bash
$ npm view ember-moment dist-tags

{ latest: '7.0.0-beta.3',
  alpha: '3.2.1-alpha.1',
  beta: '7.0.0-beta.4' }
``` 

For contrast ember-cli keeps the stable in latest.

```bash
$ npm view ember-cli dist-tags
{ latest: '2.8.0', beta: '2.9.0-beta.2' }
```

Could we avoid doing that since it makes it hard for dependency checkers to figure out what's the latest stable: 

https://github.com/tjunnone/npm-check-updates/issues/285#issuecomment-253027858

**Comment by jasonmit** [comment]
Sorry about that -- all fixed.  Thanks.
