### ISSUE TITLE
Using {{is-between}} helper does not work

### ISSUE THREAD

**Issue by tavosansal** [stefanpenner/ember-moment#194]
Trying to use the helper:
``` {{is-between date comparisonA comparisonB precision='year' inclusivity='[)'}}```
and getting the following error: ```ember.debug.js:6778 Uncaught Error: Assertion Failed: A helper named "is-between" could not be found```

Not sure if this helper is included in the latest release? I do not see it in the files inside the addon in node_modules. I have tried to uninstall and reinstalled the addon with no luck.
Thank you

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/tree/master/app/helpers

Master and by extension the README is 7.0.0-beta.  If you are pointing to stable, 6.0.0 you will not have this helper.

Hopefully that answers your question.

**Comment by tavosansal** [comment]
How does one go about installing the beta then? I don't see a tag for it?

**Comment by tavosansal** [comment]
I figured this is what I needed:  ```ember install ember-moment@7.0.0-beta.5```

**Comment by jasonmit** [comment]
@tavosansal that is correct or just `ember install ember-moment@beta`
