### ISSUE TITLE
Suggestion: better optimized intervals

### ISSUE THREAD

**Issue by ArekOsiewicz** [stefanpenner/ember-moment#198]
There is much more efficient way to do intervals instead of forcing recalculations of Helper. We should simply update property of Component and let rerender it in Ember's run-loop. Eg:

```
export default Ember.Component.extend({
  time: moment(),
  interval: 1000,
  intervalId: null,
  fromNow: "",

  didInsertElement() {
    this.refresh();
  },
  refresh() {
    var self = this;
    this.intervalId = Ember.run.later(this, function() {
      var d = moment.duration(moment().diff(this.get("time")));
      var out = "";
      if (d.asSeconds() < 120) out = parseInt(d.asSeconds()) + "s";
      else out = d.humanize();
      this.set('fromNow', out);
      this.refresh();
    }, this.get("interval"));
  },
  willDestroyElement() {
    Ember.run.cancel(this.intervalId);
  }
});

```

**Comment by jasonmit** [comment]
Components are not the same as helpers so I am having a hard time understAdding this proposal.

**Comment by ArekOsiewicz** [comment]
If you have a lot of helpers with intervals(eg 100), each recalculation of each helper is processing separately. It's killing your app.
So it's better to use component as above. ...or maybe try something with `notifyPropertyChange`.

**Comment by jasonmit** [comment]
It's not that simple because components will not work in the same way with subexpressions.  I'm happy to optimize the helper intervals but components do are not a good fit for emitting text.
