### ISSUE TITLE
duration helpers?

### ISSUE THREAD

**Issue by ksnyde** [stefanpenner/ember-moment#20]
I would love to see some duration helpers (assumes `myDuration: 45`):

    {{duration myDuration "minutes"}}   // "an hour"
    {{duration myDuration "minutes" "ago"}}  // "an hour ago"
    {{duration myDuration "minutes" "in"}} // "in an hour"

There's probably a more elegant api surface but caffeine is in short supply at the moment.

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/pull/25 Merged
