### ISSUE TITLE
message : "Assertion Failed: A helper named "moment" could not be found"

### ISSUE THREAD

**Issue by hairetdin** [stefanpenner/ember-moment#202]
Thanks for the ember-moment. I don't understand why this helper is no default in Ember?
I installed ember-moment with command: `ember install ember-moment`. When i use helper `{{moment date_created 'LLL'}}` or` {{moment date_created 'DD MM YYYY'}}` ember gives an error message: "Assertion Failed: A helper named "moment" could not be found". But the `{{moment-format date_created 'LLL'}}` works correctly. 
Information about use the ember-moment helper I read on the page https://github.com/stefanpenner/ember-moment#helpers. Is this incorrect?

**Comment by jasonmit** [comment]
What version of ember moment are you using

**Comment by henrymazza** [comment]
+1 

```
    "ember-moment": "6.1.0"
```

**Comment by jasonmit** [comment]
The moment helper is only on 7.0.0.  Which is in beta but hopefully soon I'll release.

**Comment by jasonmit** [comment]
7.0.0 was just released
