### ISSUE TITLE
issue upgrading to v7

### ISSUE THREAD

**Issue by kellyselden** [stefanpenner/ember-moment#205]
I'm having an issue upgrading to v7 https://github.com/kellyselden/package-hint-historic-resolver/pull/282

I think it's related to me having ember-cli-moment-shim v2, and that you had to revert you dep on it to v1. So if it is indeed and incompatibility between the two, this can be a tracking issue.

**Comment by jasonmit** [comment]
What is the issue?  The test failure looks like a timeout so it's not clear

**Comment by kellyselden** [comment]
Yea just a testing timeout. The app still functions normally when running, just the acceptance test using `moment-from-now` with an undefined date hangs in v7.

**Comment by jasonmit** [comment]
I'll investigate tonight, thanks.

**Comment by jasonmit** [comment]
Fixed on 7.0.3, thanks!

**Comment by kellyselden** [comment]
No, thank you.
