### ISSUE TITLE
style support?

### ISSUE THREAD

**Issue by ksnyde** [stefanpenner/ember-moment#21]
I was thinking it might be quite helpful to have results from the helpers distinguish between the *numeric* component of the return versus the contextual *text*. For instance, if the result was "3 days" this might be better represented as:

````html
<span class="numeric">3</span><span class="descriptive"> days</span>
````

I often find that making the descriptive text a slightly lighter colour helps the user understand the information more quickly. Admittedly I'm sure there would be some use cases where this would be disruptive but I'd guess it would be helpful or have no impact in a majority of cases.

Maybe added as a parameter:

    {{ago myTime stylize:true}}

Thoughts?

**Comment by lukemelia** [comment]
Maybe a better way to support this would be to have the block form of the helper yield the bound parts as block params and then the user can provide their own html as desired.

**Comment by jasonmit** [comment]
:+1: block params definitely open up some sweet possibilities.  Great idea @lukemelia

**Comment by ksnyde** [comment]
that sounds good

**Comment by jasonmit** [comment]
I'll need to convert everything to components to make this work since helpers can't currently be in a block form.

**Comment by jasonmit** [comment]
Thinking about this further, I'm not sure it can be done while also supporting locales.

I think the best way to implement this would be to just implement your own locale data containing the markup.

```
moment.locale('en', {
    relativeTime : {
        future: "in %s",
        past:   "%s ago",
        s:  "seconds",
        m:  "a minute",
        mm: "%d minutes",
        h:  "an hour",
        hh: "%d hours",
        d:  "a day",
        dd: "<span class=\"numeric\">%d</span> <span class=\"description\">days</span>",
        M:  "a month",
        MM: "%d months",
        y:  "a year",
        yy: "%d years"
    }
});
```

And then a triple curly brace on the helper, should return what you're expecting (assuming momentjs doesn't do some escaping).

**Comment by jasonmit** [comment]
Closing as it's just not feasible to be able to support this cleanly while maintaining full locale support.  My recommendation above may be the only workaround.
