### ISSUE TITLE
Using imported moment breaks instanceof check

### ISSUE THREAD

**Issue by k-g-a** [stefanpenner/ember-moment#210]
`import moment from 'moment';`
`const foo = moment();`
`const foo = moment(); //false`

Makes it harder to integrate this addon into existing project with moment.
It's also quite inconvenient in combination with ember-prop-types.

**Comment by jasonmit** [comment]
Can you paste the output of npm ls ember-cli-moment-shim and I don't see instanceof used in the snippet above.

**Comment by jasonmit** [comment]
Added a test to show it is working:
https://github.com/jasonmit/ember-cli-moment-shim/blob/master/tests/unit/utils/moment-export-test.js#L17-L19

It's most likely you were on ember-cli-moment-shim@<3.0.0

**Comment by k-g-a** [comment]
Thank you! 
The thrid line had to be the `foo instanceof moment` line (updated first post).
There was a 2.2.1 version of ember-cli-moment-shim, updating to 3.0.1 solved the problem.
