### ISSUE TITLE
Assertion Failed: Cannot call get with 'locale' on an undefined object

### ISSUE THREAD

**Issue by renpinto** [stefanpenner/ember-moment#218]
I am on ember 2.10.0 & ember-moment 7.0.1. This is how I have used it in the template,
{{moment-format '27/11/2014' 'MM/DD/YYYY' 'DD/MM/YYYY'}}

I get the following error when I try to run a unit test, 
Assertion Failed: Cannot call get with 'locale' on an undefined object.

This was working fine with ember-moment 6.1.0. 

<img width="884" alt="screen shot 2017-01-10 at 07 18 12" src="https://cloud.githubusercontent.com/assets/15615416/21797110/0c7e273e-d705-11e6-9e28-238eb526ad67.png">

**Comment by jasonmit** [comment]
Is this failing in your test specifically or is the moment-format helper also throwing in your app code?

**Comment by renpinto** [comment]
It was just the test that was failing. Adding ['service:moment'] to needs solved my issue.
Thanks for your help...
