### ISSUE TITLE
Non-working example in README

### ISSUE THREAD

**Issue by muesli** [stefanpenner/ember-moment#225]
The example

  {{moment '12-25-1995' 'MM-DD-YYYY'}}

isn't working for me as intended. It just returns the input-string - which happens to return the expected result for this example, but won't work with other timestamps.

**Comment by jasonmit** [comment]
I am unsure what you are intending.

```
{{moment '12-25-1995' 'MM-DD-YYYY'}}
```

Currently returns:
```
Mon Dec 25 1995 00:00:00 GMT-0800 {{moment '12-25-1995' 'MM-DD-YYYY'}}
```

**Comment by muesli** [comment]
Sorry, I think I simply misunderstood the API - which isn't your fault, but moment.js's... or mine ;-)
