### ISSUE TITLE
Problem with fastboot

### ISSUE THREAD

**Issue by zion03** [stefanpenner/ember-moment#226]
Trying to start my application in fastboot mode and receive:
`Error: Unable to require module 'moment-timezone' because it was not in the whitelist.`

**Comment by jasonmit** [comment]
Did you add it to fastboots whitelist?

**Comment by jasonmit** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot#whitelisting-packages

**Comment by zion03** [comment]
Thnaks, didn't notice this section in documentation.
I added to `package.json`
`  "fastbootDependencies": [
    "moment-timezone"
  ]`
And having a problem: `Cannot find module 'moment-timezone'`
What I'm doing wrong?

**Comment by zion03** [comment]
Any suggestions, I still have this problem. How to add `fastbootDependencies` correctly

Thanks

**Comment by zion03** [comment]
Solved. Application also require `"moment-timezone": "^0.5.0",`

**Comment by ehubbell** [comment]
@zion03 Running into the same issue that you had here. Curious, how exactly did you inject `"moment-timezone": "^0.0.0" into your project beyond the `package.json` file? Thanks in advance!
