### ISSUE TITLE
Using locale='es' doesn't change language to spanish

### ISSUE THREAD

**Issue by shiro-saber** [stefanpenner/ember-moment#228]
Hello, I'm wondering if theres a war to change the date output language, because using 
` {{moment-format date 'ddd DD-MMMM-YYYY' 'YYYY-MM-DD' locale='es'}}`
is not making the work, I also probe putting in the route this:
`beforeModel(){ moment.locale('es'); }`
and also not working.
And lately I tried to use it like this:
`{{moment-format date locale='es' 'ddd DD-MMMM-YYYY' 'YYYY-MM-DD'}}`
And again failed, this last crashes out the aplication.
It's there other way to do this work.

**Comment by jasonmit** [comment]
I'll assume you already configured your app to pull in all the locales:
https://github.com/stefanpenner/ember-moment#include-all-locales-into-build

This has been discussed a number of times, here is one example:
https://github.com/stefanpenner/ember-moment/issues/132

**Comment by jasonmit** [comment]
If it's still an issue, throw together an example app that can reproduce it and reopen.  But like most of the other past issues, this has been caused by another addon.

**Comment by bhernez** [comment]
Hi, I know this issue has been discussed several times, I just wonder _how can it be debugged in a project if there's any other plugin causing this conflict._ 

I mean I made an: `npm ls moment` and a `bower ls moment`, and in my case it showed:
```
├─┬ ember-cli-deploy-display-revisions@1.0.0
│ └── moment@2.18.1 
└─┬ emberfire@2.0.7
  └─┬ firebase@3.9.0
    └─┬ jsonwebtoken@7.4.0
      └─┬ joi@6.10.1
        └── moment@2.18.1 
```

```
├── elasticsearch#13.2.0
└─┬ tether-shepherd#1.8.1 extraneous
  └── tether#1.4.0
```

But I don't know if this output reflects that these plugins might be causing this behavior, and if they do, what can I do to fix it?

**Comment by jasonmit** [comment]
@bhernez I would expect to see ember-cli-moment-shim in `npm ls moment`  It's a dependency of ember-moment and it's responsible for pulling in the momentjs and locale/timezone data.
