### ISSUE TITLE
A config setting for invalid date message

### ISSUE THREAD

**Issue by musaffa** [stefanpenner/ember-moment#229]
A feature request.

Currently, if the date is invalid the template helper outputs `Invalid date`. The users might think there's something wrong in the data but if it is perfectly to valid to have empty dates. It is perhaps more desirable to display an empty `""` or `empty date` message to the user instead of showing `Invalid date`. If there were a config option (global and local) to set a message which overrides this `Invalid date` message, this could have been easily solved. So if I set `empty date` in that config setting, this `empty date` message will show up instead of `Invalid date`.

Thanks.

**Comment by jasonmit** [comment]
You can configure it to accept empty dates to avoid the Invalid Date:
https://github.com/stefanpenner/ember-moment/blob/92a75466ce08715720204589e710481dd7b41dd7/README.md#global-allow-empty-dates

As for configuring the error message, "Invalid Date," that's handled internally within momentjs and I don't know off the top of my head if their is an API to configure it.

Happy to consider a pull request.

**Comment by musaffa** [comment]
I've already configured `allowEmpty` to `true` but `Invalid date` message is still an issue.

**Comment by jasonmit** [comment]
@musaffa do you know what the value (empty string, null, or an invalid date string, etc.) you are passing into the helper is?  Which helper are you using?

**Comment by musaffa** [comment]
I'm using `moment-format` helper. As this helper already handles invalid dates, I don't to want to handle invalid dates myself. All I want is the ability to override the default output message with invalid dates.

[This](http://stackoverflow.com/a/38955292/479407) answer in SO suggests using `moment.js`' locale to override the message:
```Javascript
moment.updateLocale(moment.locale(), { invalidDate: "empty date" })
```

**Comment by jasonmit** [comment]
@musaffa I'd expect that to hold true, have you tested that against ember-moment?  Assuming you are on the latest, I'd expect that to work.

**Comment by musaffa** [comment]
I tried but it didn't work. `ember-moment` probably doesn't support `updateLocale`.

**Comment by jasonmit** [comment]
@musaffa ember-cli-moment-shim (the thing you import `moment` with) is a very thin wrapper around momentjs and it looks like it's private, `_invalidDate`, I would defer to opening an issue within momentjs if you need first-class support for changing this string.
