### ISSUE TITLE
Could not load when --environment=production

### ISSUE THREAD

**Issue by zhuoqiang** [stefanpenner/ember-moment#23]
while works under development environment, however, the web page could not be loaded when serve under production environment with the following error:

    Uncaught Error: Could not find module ember-moment/helpers/moment

Here's the same problem and workaround:
http://stackoverflow.com/questions/25018160/ember-cli-fails-on-environment-production-uncaught-error-could-not-find-modu

**Comment by jasonmit** [comment]
Closing as this isn't ember-moment related.
