### ISSUE TITLE
How can I set short month for locale?

### ISSUE THREAD

**Issue by vashchenkov** [stefanpenner/ember-moment#230]
I need to change short month in moment.
But I can't do it.
I have try to set 
`localeOutputPath: 'assets/moment-locales'`
And call 
`Ember.$.getScript('/assets/moment-locales/ru.js');`

In this case i have ember-mirage error 
`Your Ember app tried to GET '/assets/moment-locales/ru.js?_=1490191145335',
         but there was no route defined to handle this request.
         Define a route that matches this path in your
         mirage/config.js file`

Is it simple way to set short months name for moment?

**Comment by jasonmit** [comment]
@vashchenkov this is more a momentjs question but this should give you the data you want:

```js
moment.localeData('ru').monthsShort();
```
