### ISSUE TITLE
includeTimeZone: '2010-2020' broken

### ISSUE THREAD

**Issue by kekbur** [stefanpenner/ember-moment#231]
The latest release of moment-timezone (0.5.12) has broken the ember-moment configuration option ```includeTimeZone: '2010-2020'```. The new truncated time zone data file covers years 2012-2022.

```
$ ember build -prod
[...]
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat '[...]/tmp/funnel-input_base_path-qB4w31tO.tmp/builds/moment-timezone-with-data-2010-2020.js'
```

Trying to use ```2012-2022``` as the configuration value produces the following output:

```
$ ember build -prod
ember-moment: Please specify the moment-timezone dataset to include as either "all", "2010-2020", or "none".
```

Would it be possible to support configuration value ```truncated```, which would automatically select the current truncated time zone dataset?

**Comment by joestein216** [comment]
Seems like ember-moment is doing the right thing and moment-timezone introduced a breaking change in a patch release.

This workaround kept me going today:

https://github.com/moment/moment-timezone/issues/466

I can't really think of a way to keep the includeTimeZone options in sync with moment-timezone unless moment-timezone also followed and provided a 'truncated' option; which sounds like a more robust solution.

Maybe 'recent' over 'truncated'

**Comment by jasonmit** [comment]
I release ember-cli-moment-shim 3.0.3 to lock the dep to <= 0.5.11 and I'm in the process of versioning 3.0.4 which will support 2010-2020, 2012-2022 but will encourage users to use the option "subset" to signify you only want the subset of data.  This way we're not dealing with this again in a few years.

**Comment by jasonmit** [comment]
3.1.0 was just versioned with the deprecation of "2010-2020" and the new option name "subset" (will scale better :)).

**Comment by rwwagner90** [comment]
Can someone better explain how these subsets work? It saves some bytes to use the subset, instead of all, but I am unclear on when they change and if it might break things.
