### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bartocc** [stefanpenner/ember-moment#237]
7.3.0 was released Jan 7, 2017 but since, ember-macro-helpers has been updated a few times.

Wouldn't it be appropriate to cut a new release ?

PS: on a side note, looks like tags have not beed added to the repo since 7.0.1

Ju

**Comment by jasonmit** [comment]
@kellyselden any chance you can help bring ember-moment up to the latest API?

**Comment by kellyselden** [comment]
@jasonmit done #238

**Comment by jasonmit** [comment]
Included in 7.3.1
