### ISSUE TITLE
interval not recomputing properly with (now)

### ISSUE THREAD

**Issue by rwwagner90** [stefanpenner/ember-moment#248]
I tried using the `now` helper and it never recomputes:

`{{moment-format (now) 'LT' interval=1000}}`

However, if I pass undefined, it does recompute:

`{{moment-format undefined 'LT' interval=1000}}`

Any ideas on this? Would like to be able to pass `(now)` instead of `undefined`.

**Comment by jasonmit** [comment]
I believe you want `{{moment-format (now interval=1000) 'LT'}}`

**Comment by jasonmit** [comment]
Feel free to reopen if this continues to be an issue

**Comment by rwwagner90** [comment]
@jasonmit shouldn't we update the README then? It doesn't show that here https://github.com/stefanpenner/ember-moment#live-updating-of-displayed-time

**Comment by jasonmit** [comment]
@rwwagner90 thanks for calling that out - I've updated accordingly and sorry the docs mislead you!
