### ISSUE TITLE
Implement Ember.Copyable

### ISSUE THREAD

**Issue by Techn1x** [stefanpenner/ember-moment#263]
Obviously it's easy to copy a moment just by wrapping it in moment(), but if I wanted to copy a moment using `Ember.copy(value, true)` then moment needs to implement Ember.Copyable for this to work

Is this possible?

A use case could be having an object like the following;
```
let momentHash = {
  momentA: moment(),
  momentB: moment(),
  momentC: moment.duration(6, 'hours'),
}
```
Then wanting to do `Ember.copy(momentHash,true)`

Thoughts?

**Comment by jasonmit** [comment]
You'll want to open this against ember-cli-moment-shim.
