### ISSUE TITLE
Update as time passes?

### ISSUE THREAD

**Issue by jmurphyau** [stefanpenner/ember-moment#27]
This is to get thoughts on having the {{ago}} helper update as time passes..

I've been playing around with it but haven't got it quite there yet.. I've been doing it in HTMLBars only though - returning a stream that gets notified at the point in time that the string is expected to have changed.

Should the computed property and the helper update as time passes? For `ago`, I'm not really clear on the use cases for the computed property, if not to display in a template (which the helper covers).

- 0 to 45 seconds = 'a few seconds ago'
- 45 to 90 seconds = 'a minute ago'
- 90 seconds to 45 minutes = '2 minutes ago ... 45 minutes ago'
- 45 to 90 minutes = 'an hour ago'
- 90 minutes to 22 hours = '2 hours ago ... 22 hours ago'
- 22 to 36 hours = 'a day ago'
- 36 hours to 25 days = '2 days ago ... 25 days ago'
- 25 to 45 days = 'a month ago
- 45 to 345 days = '2 months ago ... 11 months ago'
- 345 to 547 days (1.5 years) = 'a year ago'
- 548 days+ = '2 years ago ... 20 years ago'

**Comment by jasonmit** [comment]
I agree.  I believe it's not rerendering since the underlying value is typically a constant, some moment in time.  Perhaps we add some loop to force the rerender?

**Comment by jmurphyau** [comment]
It makes sense that the value is not updating - I wouldn't expect it to. I only opened this as an 'issue' since it seems the most appropriate place (maybe a PR instead?)

I've started work and have some logic to work out when the value of the {{ago}} helper will change - see https://github.com/jmurphyau/ember-moment/tree/update-as-time-passes.

Using this would help with working out which value should be used in setting Ember.run.later to trigger rerender.. How would you trigger a rerender though? With HTMLBars I call a 'notify' on the stream but this only covers HTMLBars - if theres a 'rerender' type function/trigger that applies across both Handlebars and HTMLBars that might be the way to go.

**Comment by jasonmit** [comment]
@jmurphyau I'd be fine if this "rerendering" functionality was only supported on HTMLBars.

**Comment by lukemelia** [comment]
I would prefer that this be opt-in behavior, or at least have the ability to be opt-out. I can imagine updating automatically updating timestamps being too distracting in many UIs.

**Comment by runspired** [comment]
I'm just peeking around on this addon (I have my own moment helpers but wondering what new is out there), the `clock` or `tick` pattern is what I use, and I differentiate between live and non-live by exposing duplicate helpers named `moment-foo` and `live-moment-foo`

**Comment by jasonmit** [comment]
I was planning to make it driven by an argument `interval`.  `interval` 0 by default meaning it will never recalculate.  This is also even easier with the new Ember.Helper which has the ability to recompute to trigger a rerender.  But I am also not against having separate helpers live vs non-live.
