### ISSUE TITLE
is-same randomly fails - really!

### ISSUE THREAD

**Issue by medokin** [stefanpenner/ember-moment#277]
Ember 2.18
ember-moment 7.7.0

```hbs
{{moment-format model.beginning 'dddd DD. MMMM YYYY, HH:mm'}} Uhr -
{{#if (is-same model.beginning model.end 'day' interval=100)}}
  {{moment-format model.end 'HH:mm'}} Uhr
{{else}}
  {{moment-format model.end 'dddd DD. MMMM YYYY, HH:mm'}} Uhr
{{/if}}
```
![2018-05-14_14-26-31](https://user-images.githubusercontent.com/456683/39997344-deee9998-5782-11e8-9486-ca61a3e92ffa.gif)

Maybe related to https://github.com/stefanpenner/ember-moment/issues/272

**Comment by jasonmit** [comment]
Can you write a fail test?
