### ISSUE TITLE
Feature Request: moment-range

### ISSUE THREAD

**Issue by erichonkanen** [stefanpenner/ember-moment#286]
It would be great if this library contained a template helper to automatically create a range of dates using [moment-range](https://github.com/rotaready/moment-range)

**Comment by BenjaminBeck** [comment]
Or alternative:
https://www.npmjs.com/package/ember-cli-cjs-transform
and https://www.npmjs.com/package/moment-range

ember-cli-build.js:
``` 
app.import('node_modules/moment-range/dist/moment-range.js',{
    using: [
        { transformation: 'cjs', as: 'moment-range'}
    ]
});
```
your-componen.js:
``` 
import momentRange from 'moment-range';
import momentTime from "moment";
const moment = momentRange.extendMoment(momentTime);
...
let range = moment.range(beginMoment, endMoment);
...
```
