### ISSUE TITLE
`import moment from 'moment';` does not work

### ISSUE THREAD

**Issue by brandynbennett** [stefanpenner/ember-moment#292]
When I use `import moment from 'moment';` as the README specifies I get an error that the module can't be found. Is this because `ember-cli-moment-shim` is a `devDependency` instead of a `dependency`?? Using version 7.7.0 of this addon

**Comment by aaronlelevier** [comment]
I installed the package earlier today, and was able to use the `import moment from 'moment';` inside of a component fine.

**Comment by jasonmit** [comment]
Unable to reproduce, closing.  If you put together a reproduction of the issue please create a new issue.
