### ISSUE TITLE
ES6 moment doesn't use correct defaultFormat

### ISSUE THREAD

**Issue by ControlTheBit** [stefanpenner/ember-moment#294]
I have the following definition for moment in my environment.js:
```
moment: {
      includeLocales: ['is'],
      outputFormat: 'YYYY-MM-DDTHH:mm:ss'
}
```

The outputFormat is _correctly_ applied to {{moment-format}}, but not to the moment object that can be used in ES6.

I import the moment object like this `import moment from 'moment';` and use it like this in an action inside a component `this.set('data.myDateAsString', moment(dateObjectFromUi).format());`. The output that I get is formatted in the original default format and not in the default format that I defined in the environment.js.

_Used Versions:_

- "ember-moment": "^7.8.0"
- "ember-cli": "^3.5.1"

**Comment by jasonmit** [comment]
`outputFormat` config option is used only in helpers and computeds.  Not when interfacing with the moment API directly.  This is behaving as expected.
