### ISSUE TITLE
DEPRECATION: Use of `merge` has been deprecated

### ISSUE THREAD

**Issue by raphaelns-developer** [stefanpenner/ember-moment#297]
`DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead. [deprecation id: ember-polyfills.deprecate-merge] See https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge for more details.`

"ember-source": "~3.7.0",
"ember-moment": "7.7.0"

**Comment by jasonmit** [comment]
Should be resolved, feel free to comment if it's still appearing.
