### ISSUE TITLE
add other helpers?

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-moment#3]

**Comment by kenips** [comment]
:+1: looking forward to this too. If possible please default to UTC.

**Comment by nflbeezy** [comment]
:+1: I'd love to have timezone support in the component. Agree with @kenips that UTC should be default

**Comment by jasonmit** [comment]
I have this implemented in ember-intl, which relies on the native Intl API.  I will try and get the PR for this in.
