### ISSUE TITLE
Readme missing moment-add + moment-subtract helpers

### ISSUE THREAD

**Issue by Techn1x** [stefanpenner/ember-moment#300]
I noticed that this package has two extra helpers, `{{moment-add number precision}}` and `{{moment-subtract number precision}}` and only found out about these from searching PRs and issues to see if someone had already asked for these helpers

If I find some time I can try to write some documentation for them, but someone more familiar with using them might be able to do this quicker

**Comment by TristanToye** [comment]
I'll take some time to try add some docs for this. I have been using this package for years and didn't know these helpers existed!
