### ISSUE TITLE
"Invalid date" in Safari

### ISSUE THREAD

**Issue by Redsandro** [stefanpenner/ember-moment#323]
Using a `pickupDate` from my model as `DS.attr('date')`, I can't use `moment-format` in Safari like so:

```
{{moment-format model.pickupDate 'Y-MM-DD HH:mm'}}
```

It will show:

> Invalid date

This issue is similar to the previously closed #187. The bug was closed by @ihomp after commenting:

> I had in my model:
> `bookingDate: DS.attr('date'),`
> changed to
> `bookingDate: DS.attr('string'),`

However, this is a workaround, not a fix for this issue. The [documentation](https://github.com/stefanpenner/ember-moment#moment-from--moment-from-now) states that the date passed to moment-format can be:

> Any value(s) interpretable as a date/time by `moment` (a `date` String or a `Moment` or a `Date`...)

So I am passing a Date. It should work. If I pass this to `moment` in Safari manualy:

```
moment(new Date()).format('Y-MM-DD HH:mm')
```

It works as expected.

Why does the date get invalid in Safari after being passed through `moment-format`?

**Comment by jasonmit** [comment]
Can you tell me what the stringified value of bookingDate is in Safari and non-Safari?  Can you replicate this without using ember-data?
