### ISSUE TITLE
helpers within htmlbars are not bound

### ISSUE THREAD

**Issue by jasonmit** [stefanpenner/ember-moment#34]

**Comment by btecu** [comment]
I'm trying to use `ember-moment` with `ember 1.11.0-beta.4` but all my dates are **today** when using the {{moment}} helper. Is this the same issue?

**Comment by btecu** [comment]
If you need I can provide a sample repository reproducing the issue.

**Comment by jasonmit** [comment]
@btecu it's related, I can reproduce.  Will have a fix shortly

**Comment by btecu** [comment]
Thanks. Bump to 1.1.1?

**Comment by jasonmit** [comment]
Done
