### ISSUE TITLE
Add additional date format helpers from ember-cli-dates?

### ISSUE THREAD

**Issue by johnotander** [stefanpenner/ember-moment#36]
Hello,

I'm the maintainer of [ember-cli-dates](https://github.com/johnotander/ember-cli-dates). There's definitely a lot of overlap between these two projects as pointed out in johnotander/ember-cli-dates/issues/19, so I was hoping to combine efforts and collaborate on a single, cohesive project. This project has significantly more functionality, but is missing some of the date helpers that `ember-cli-dates` currently provides.

So, I'm wondering if you all have any interest in adding some of the helpers like `day-of-the-week`, `month-and-day`, and `month-and-year`, etc.? I'd be happy to open up a PR if this is something that this project would be interesting in incorporating. Or, perhaps the helpers could be broken off into an `ember-moment-helpers` addon, which end users can optionally install in order to incorporate a collection of helpers regarding dates and times?

Any thoughts or insight would be greatly appreciated, I'd love to collaborate and combine efforts.

Best,

John Otander

**Comment by stefanpenner** [comment]
> So, I'm wondering if you all have any interest in adding some of the helpers like day-of-the-week, month-and-day, and month-and-year, etc.? I'd be happy to open up a PR if this is something that this project would be interesting in incorporating. Or, perhaps the helpers could be broken off into an ember-moment-helpers addon, which end users can optionally install in order to incorporate a collection of helpers regarding dates and times?

adding it here seems appropriate for now. We will soon have better support for peerAddons, which would allow ember-moment and ember-moment-helpers to nicely exist.

**Comment by stefanpenner** [comment]
> Any thoughts or insight would be greatly appreciated, I'd love to collaborate and combine efforts.

+10000

**Comment by jasonmit** [comment]
:+1:

**Comment by btecu** [comment]
`day-of-the-week`: {{moment today 'dddd'}} // Wednesday
`month-and-day`: {{moment today 'MMMM Do'}} // March 11th
`month-and-year`: {{moment today 'MMM YYYY'}} // Mar 2015

So, current implementation supports all the mentioned helpers and it may be enough.
http://momentjs.com/docs/#/displaying/

Maybe renaming `{{moment}}` to something like `{{moment-format}}` will make more obvious the availability of this feature?

I can also add a few more examples to the documentation if you think it would help.

**Comment by jasonmit** [comment]
@johnotander any progress on this?  I'd be willing to help

**Comment by elwayman02** [comment]
:+1:, I'd love to see more opinions on @btecu's latest comment. It may makes sense not to add new helpers if the same functionality can be achieved simply by better documenting how to use `ember-moment` in conjunction with the features `moment` already provides.

**Comment by jasonmit** [comment]
Everything is already renamed.  What's left?

**Comment by elwayman02** [comment]
Ah, didn't see that haha. Maybe this issue should be closed and ember-cli-dates README updated with a mention that ember-moment now incorporates that functionality?

**Comment by jasonmit** [comment]
Want to update the docs? :)
