### ISSUE TITLE
Name helpers more inline with moment

### ISSUE THREAD

**Issue by btecu** [stefanpenner/ember-moment#37]
It would be good to have `ember-moment` helpers follow `Moment.js` naming.
For instance, we have a helper called `ago` for relative time. It should probably be called `fromNow` or `relative` since it also works for future dates:
```
{{ago pastDate}} // 3 years ago
{{ago futureDate}} // in 2 weeks
```

`moment` helper is very generic named and maybe it would be better named `format`.
`duration` is named properly, since it's named exactly like that in `Moment.js`.

I realize those names are too generic, so maybe it would be better to prefix them, like `moment-format`, `moment-duration` ...

**Comment by Eptis** [comment]
+1 I was very confused about this when I noticed that the `moment` helper is different from the `moment` function. having this `moment` name also conflicts with other uses of moment.js

**Comment by bhoskins** [comment]
Amen

**Comment by stefanpenner** [comment]
Great idea. PR that installs the new addons and deprecates the old would be accepted

**Comment by Eptis** [comment]
Will check if I can do a PR tomorrow. Thanks!


—
Met vriendelijke groet / Kind regards,


Dennis Tel

**Comment by stefanpenner** [comment]
> Will check if I can do a PR tomorrow. Thanks!

:+1:

**Comment by jasonmit** [comment]
I will work on bringing over @Eptis changes to 3.x tonight.
