### ISSUE TITLE
Addon Woes with ember-cli 0.2.0 and ember 1.10.0

### ISSUE THREAD

**Issue by Goldcap** [stefanpenner/ember-moment#38]
Hey Stefan, thanks for this!

I do note that in my current build (node 0.12.0, Vanilla ember-cli 0.2.0, ember 1.10.0) I get the following error, using moment in a transformer:

```javascript
Error: Could not find module `ember-moment/helpers/moment` imported from `ember-app/initializers/ember-moment`. 
```

I really have nothing else going on, so not sure what's up, but it was working with a GLOBAL and Brocfile.js import on 0.15.0 and 1.9.0, so maybe something with the loader?

```javascript
import DS from "ember-data";
import moment from 'ember-moment';

var IsodateTransform = DS.Transform.extend({  
  deserialize: function (serialized) {
    if (serialized) {
      return moment(serialized).toDate();
    }
    return serialized;
  },

  serialize: function (deserialized) {
    if (deserialized) {
      return moment(deserialized).format();
    }
    return deserialized;
  }
});

export default IsodateTransform;
```

**Comment by stefanpenner** [comment]
looking

**Comment by stefanpenner** [comment]
cant seem to replicate, given:

```
ember version                                                                                                                                                                                            
> version: 0.2.0
> node: 1.5.1
> npm: 2.7.0
```

I did:

```sh
ember new test-moment
cd test-moment
ember install:addon ember-moment
```

then I added to application.hbs

```
{{moment date}}
{{ago date}}
{{duration ms}}
```

and everything appears to work

![Uploading Screen Shot 2015-03-23 at 9.52.17 AM.png . . .]()


example repo: https://github.com/stefanpenner/__test-moment
commit that did stuff: https://github.com/stefanpenner/__test-moment/commit/59c2e222e29116ef99b829384a2115784082199c

**Comment by stefanpenner** [comment]
Now, i don't doubt something is funky. I am just unable to reproduce, can you help me reproduce?

**Comment by Goldcap** [comment]
Yes, hey, totally can do! I had this in a transformation, maybe something in ember data, or me :) Let me get you a repo with all the stuff in it, but later probably this evening.

**Comment by brzpegasus** [comment]
FYI, I ran into this issue as well when upgrading an existing project. Things do work fine in Ember 1.10.0 and 1.11.0, however. It's only complaining with Ember Canary:

```
Uncaught Error: Could not find module `ember-moment/helpers/moment` imported from `test-moment/initializers/ember-moment`
```

Repo: https://github.com/stefanpenner/__test-moment/compare/master...brzpegasus:ember-canary

I haven't investigated the error yet so I'm unclear whether it's even an ember-moment issue, but since this was opened not too long ago, I figured I'd toss in that extra info.

**Comment by Goldcap** [comment]
Yes, I was also on canary. And apologies in advance for not getting back to
this, still working on getting some time to get a proper example together.

On Tue, Mar 31, 2015 at 3:18 PM, Estelle DeBlois <notifications@github.com>
wrote:

> FYI, I ran into this issue as well when upgrading an existing project.
> Things do work fine in Ember 1.10.0 and 1.11.0, however. It's only
> complaining with Ember Canary:
>
> Uncaught Error: Could not find module `ember-moment/helpers/moment` imported from `test-moment/initializers/ember-moment`
>
> Repo: stefanpenner/__test-moment@master...brzpegasus:ember-canary
> <https://github.com/stefanpenner/__test-moment/compare/master...brzpegasus:ember-canary>
>
> I haven't investigated the error yet so I'm unclear whether it's even an
> ember-moment issue, but since this was opened not too long ago, I figured
> I'd toss in that extra info.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefanpenner/ember-moment/issues/38#issuecomment-88215974>
> .
>



-- 
"Period Three Implies Chaos. Period Three Implies Chaos. Period Three
Implies Chaos.
<https://play.spotify.com/album/7tcmxxo0cHzfozgW8io0OS?play=true&utm_source=open.spotify.com&utm_medium=open>"
-
James A. Yorke <http://en.wikipedia.org/wiki/James_A._Yorke>

**Comment by brzpegasus** [comment]
So I think this can be closed. It isn't an issue with ember-moment at all. It's a problem with Ember Data not working with the current Ember Canary. Has to do with the new CP syntax:

```
Uncaught Error: Assertion Failed: Computed properties that define a setter cannot be read-only
```

That is preventing the rest of the code (including ember-moment) from loading properly. If you removed ember-data as a dependency, it works.

**Comment by Goldcap** [comment]
Yep, agreed, and thanks Estelle for providing some clarity. Live by the
canary, die by the canary.

On Tue, Mar 31, 2015 at 3:44 PM, Estelle DeBlois <notifications@github.com>
wrote:

> So I think this can be closed. It isn't an issue with ember-moment at all.
> It's a problem with Ember Data not working with the current Ember Canary.
> Has to do with the new CP syntax:
>
> Uncaught Error: Assertion Failed: Computed properties that define a setter cannot be read-only
>
> That is preventing the rest of the code (including ember-moment) from
> loading properly. If you removed ember-data as a dependency, it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefanpenner/ember-moment/issues/38#issuecomment-88223300>
> .
>



-- 
"Period Three Implies Chaos. Period Three Implies Chaos. Period Three
Implies Chaos.
<https://play.spotify.com/album/7tcmxxo0cHzfozgW8io0OS?play=true&utm_source=open.spotify.com&utm_medium=open>"
-
James A. Yorke <http://en.wikipedia.org/wiki/James_A._Yorke>

**Comment by jasonmit** [comment]
Thanks all, it seems we arrived to a resolution.

**Comment by al3x-edge** [comment]
Ran into this just like @brzpegasus.  Anyone happen to know if there is an issue tracking this on ember-data? Can't seem to find one.

**Comment by amedrz** [comment]
Just hit a wall with this one. @brzpegasus is there an issue on ember data linked to this?

**Comment by brzpegasus** [comment]
@amedrz Hmm, feels like such a long time ago, I barely recall this issue. What version of ember-moment, ember, and ember-data are you using?

**Comment by amedrz** [comment]
@brzpegasus Ember 1.13.5, Ember data 1.13.7 and moment-cli ^3.2.0

**Comment by jasonmit** [comment]
Post the full stack trace and if you can reproduce in an isolated app would speed up the patch process.

**Comment by amedrz** [comment]
@jasonmit nevermind, I was on the middle of an ember upgrade and got confused about this. Now it's working as it is.

**Comment by jasonmit** [comment]
:+1: awesome, I know how those can be :)

**Comment by lmcardle** [comment]
I get this issue on a brand new project, using: Ember 1.13.7 and Ember Data 1.13.8.

```
ember new momentTest
cd momentTest
ember install ember-moment
```
Then in application.hbs
```
{{moment date}}
```
Start the server and get the error:
```
Uncaught Error: Assertion Failed: A helper named 'moment' could not be found
```

**Comment by jasonmit** [comment]
There isn't such thing as a moment helper.  See the README: https://github.com/stefanpenner/ember-moment on how to use this lib.

**Comment by zen-tmq** [comment]
The README does actually still mention the {{moment}} template helper. Are you saying this is incorrect and it has been removed? If so, maybe the README can be updated to include only supported functionality?

**Comment by jasonmit** [comment]
The README targets master which is still beta.  Beta has the moment helper, latest does not
