### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by jwhitmarsh** [stefanpenner/ember-moment#42]
Can we have a setting to handle 'null' dates silently?

**Comment by olivierlesnicki** [comment]
+1

**Comment by stefanpenner** [comment]
I suspect the output should be null? The question is, what inputs should generic null and which inform of invalid date. It seems fishy to just swallow all invalid dates, as I would imagine it would be a tricky thing to debug.

**Comment by olivierlesnicki** [comment]
The output should indeed be null. I suppose all JavaScript falsy values should generate `null`. 
Any truthy value should throw the appropriate error.

**Comment by stefanpenner** [comment]
Maybe we offer a configurable set of options:

handle invalid date as:

* throw
* null

**Comment by jasonmit** [comment]
How about just an Ember.Logger.warn to get a warning in dev but silent in prod?

**Comment by stefanpenner** [comment]
> How about just an Ember.Logger.warn to get a warning in dev but silent in prod?

sure.

**Comment by jwhitmarsh** [comment]
:+1:
