### ISSUE TITLE
Ago Component Input Date for 2015-02-04T03:19:51.000Z

### ISSUE THREAD

**Issue by selbyk** [stefanpenner/ember-moment#44]
So, I've been using this for awhile on [selby.io/blog](http://www.selby.io/blog) and it's been bugging me.

I've been passing in sqlite's date format, which is like `2015-02-04T03:19:51.000Z`:

```hbs
{{ago post.created_at}}
```

And it gives a pseudo-random number of hours ago: `17 hours ago`. Today I attempted to pass in an input format:

```hbs
{{ago post.created_at "YYYY-MM-DDTHH:mm:ss.000Z"}}
```

But now it's giving me years. `2012 years ago`

Any ideas? Thanks for any help you can give. 

Great component, btw.

**Comment by selbyk** [comment]
Just kidding.  Production npm repo was behind, updating fixed it.

**Comment by stefanpenner** [comment]
Woop
