### ISSUE TITLE
Configurable default moment format

### ISSUE THREAD

**Issue by Kilowhisky** [stefanpenner/ember-moment#49]
Right now moment format is hard coded to: `LLLL`. I've love the ability to globally set the default format to something else besides having to pass it into every moment function. 

If at all possible it would be great to tie it to the locale enhancement so formats could changed based on language selected. (issue https://github.com/stefanpenner/ember-moment/issues/14)

**Comment by stefanpenner** [comment]
any ideas on where this config should live?

**Comment by Kilowhisky** [comment]
That sounds like a great place!

**Comment by jasonmit** [comment]
Working on this tonight

**Comment by stefanpenner** [comment]
@jasonmit <3

**Comment by jasonmit** [comment]
> If at all possible it would be great to tie it to the locale enhancement so formats could changed based on language selected. (issue #14)

I'm not sure this is needed since locale data implements what `LLLL` is on a per-locale basis.

For example, `fr` locale dictates to render `L` as `DD/MM/YYYY` and under `en` `L` is `MM/DD/YYYY`
