### ISSUE TITLE
moment is not defined

### ISSUE THREAD

**Issue by ksnyde** [stefanpenner/ember-moment#59]
I just upgraded from Ember CLI `0.2.7` to `1.13.1` and updated the ember-moment (npm: `2.0.0`) and ember-cli-moment-shim (bower: `0.3.1`) to the latest. I have install moment on the bower side at version `2.10.3`. 

Should be the latest and greatest for all but when I start serving the application the application compiles/transpiles I immediately get a:

> Uncaught ReferenceError: moment is not defined

The stack trace is:

	(anonymous function)	@	index.js:5
	mod.state	@	loader.js:141
	tryFinally	@	loader.js:21
	requireModule	@	loader.js:139
	requireFrom	@	loader.js:112
	reify	@	loader.js:97
	mod.state	@	loader.js:140
	tryFinally	@	loader.js:21
	requireModule	@	loader.js:139
	requireFrom	@	loader.js:112
	reify	@	loader.js:97
	mod.state	@	loader.js:140
	tryFinally	@	loader.js:21
	requireModule	@	loader.js:139
	requireFrom	@	loader.js:112
	reify	@	loader.js:97
	mod.state	@	loader.js:140
	tryFinally	@	loader.js:21
	requireModule	@	loader.js:139
	(anonymous function)	@	ember-load-initializers.js:24
	default	@	ember-load-initializers.js:21
	(anonymous function)	@	app.js:15
	mod.state	@	loader.js:141
	tryFinally	@	loader.js:21
	requireModule	@	loader.js:139
	(anonymous function)	@	app-boot.js:25

Am I doing anything obviously wrong?

**Comment by jasonmit** [comment]
I cut 2.0 last night and may have introduced a regression.  Will look into it today.

If you could publish a demo app with this issue it could speed up the debugging process.

**Comment by ksnyde** [comment]
The app I encountered it on is not OSS but let me see if I can recreate outside of that app.

**Comment by jasonmit** [comment]
Awesome, thanks :+1:

**Comment by jasonmit** [comment]
I have been able to reproduced it, will work on a fix shortly

**Comment by ksnyde** [comment]
ok great

**Comment by jasonmit** [comment]
I just released 2.0.1 which appears to work around a limitation of nested addons within ember-cli.  Can you `ember install ember-moment` again you may need to `rm -rf node_modules/ember-moment`

**Comment by ggstuart** [comment]
Hi, 

My app is working perfectly but I'm getting an annoying JSHint error `'moment' is not defined`. Is there something I need to do to avoid this?

**Comment by jasonmit** [comment]
@ggstuart I need more information than this.  Does the linter provide anymore context (module, filename, line number)

**Comment by ggstuart** [comment]
Its within my own component, I am calling moment myself.

I am loading a 'blob' of json data as an attribute in one of my models without specifying the details as further models. The data are complex, variable and read-only in this context.

So I am trying to parse this json within a component by loading the date strings into moment objects. Is this a bad pattern? I seem to have access to moment as it works perfectly, I just get this annoying jshint error.

**Comment by jasonmit** [comment]
Did you 'import moment from "moment"' at the top of the module?

**Comment by ggstuart** [comment]
Thanks, I'm not sure I understand why it works without that. The warning message is gone.

**Comment by jasonmit** [comment]
It's still accessible as a global, that likely will not change anytime soon.
