### ISSUE TITLE
Uncaught ReferenceError: moment is not defined with 2.0

### ISSUE THREAD

**Issue by benedikt-d** [stefanpenner/ember-moment#61]
I'm not able to load ember moment with the 2.0 version:

Uncaught ReferenceError: moment is not defined

**Comment by jasonmit** [comment]
Are you using 2.0.1 and did you use ember install to install ember-moment?

**Comment by benedikt-d** [comment]
I'm using Ember 1.13.4 and updating with npm install and changing the version of ember moment in the package.json from "ember-moment": "1.1.1", to "ember-moment": "2.0.0" before.

**Comment by jasonmit** [comment]
ember install ember-moment@2.0.1
