### ISSUE TITLE
moment.locale() does not work

### ISSUE THREAD

**Issue by Marthyn** [stefanpenner/ember-moment#66]
Hi,

i tried using
```
// app/routes/applicaton.js
import moment from 'moment';

export default Ember.Route.extend({
  beforeModel() {
    // sets the application locale to Dutch
    moment.locale('nl');
  }
});
```

But it doesn't set the language at all, it still stays at 'en'. Anything else i need to configure first to make this work? 
(im on the latest version)

**Comment by jasonmit** [comment]
Strange, will investigate tonight.  Is your app public?  Did you include the locals via your app config?

**Comment by Marthyn** [comment]
Sorry forgot to close this, it was my fault I didn't include the locales, I expected them to be included since moment includes it standard. Maybe add that to the readme?

**Comment by jasonmit** [comment]
I can make it so it includes all by default but few apps will target all the locales, so that won't be optimal.  Feel free to send a quick readme patch to cover the issue you found.

**Comment by jasonmit** [comment]
https://github.com/stefanpenner/ember-moment/releases/tag/3.1.0 be sure to re-install via `ember install` since the generator needs to run.

**Comment by Marthyn** [comment]
Oh awesome! Thank you :)
