### ISSUE TITLE
issue testing page with moment-from-now

### ISSUE THREAD

**Issue by Iftahh** [stefanpenner/ember-moment#80]
My acceptance tests stopped working in pages where I added the `moment-from-now` with an interval.

The tests start with `visit` to a url, followed by `andThen` containing the asserts.
Unfortunately the tests fail with a timeout and the `andThen` isn't called.

I'm guessing the problem is the endless `Ember.runLater` that the testing framework waiting for all the jobs queue to empty before activating the next `andThen`.

Without passing an interval to the moment-from-now the tests work as expected.

This issue isn't specific to ember-moment.  It was reported to Ember since 2013 and still is open - see https://github.com/emberjs/ember.js/issues/3008
@teddyzeenny provided a workaround in that thread, ie. instead of `runLater` use:
`setTimeout(function() { Em.run(function() { //.. code here } });`

**Comment by jasonmit** [comment]
Ember.run.cancel to cancel anything outstanding on the run loop queue.  It's something you want to get into the habit with testing.

**Comment by Iftahh** [comment]
@jasonmit  Perhaps I misunderstood you, or you misunderstood me...
the testing code looks like this:

```javascript
test: function() {
   visit("/pending-users");
   andThen(function() {
      assert(...page contains what is expected...);
   }
}
```
Where would I place the cancel?  The only place that makes sense is between the `visit` to the `andThen`.
What timer should I pass to the cancel?  it accepts a parameter, but there is no way to know the runlater timer set by ember-moment.
Attempting to use instead the (private) method `Ember.run.cancelTimers()`  failed even more tests... I did not debug exactly why.

**Comment by jasonmit** [comment]
@Iftahh sorry, I do think I misunderstood.  Is your project public so I can step through this?

@stefanpenner have anything better in mind than replacing the Ember.run.later with setTimeout + Ember.run?

https://github.com/stefanpenner/ember-moment/blob/master/addon/helpers/moment-from-now.js#L12

**Comment by stefanpenner** [comment]
@jasonmit seems like the timer should be canceled in `destroy()`

**Comment by jasonmit** [comment]
:+1: will fix shortly

**Comment by stefanpenner** [comment]
that wont help the above issue, as the timerwaiters in the test helpers are not granular enough.

The solution in ember will land shortly have async/await is supported in jshint, which will revamp the test helpers. Long story, upside  @Teddyzeenny and myself spike it was ember conf, it was wonderful and glorious but was blocked on tooling (just jshint) support, and stage 2 TC39 support.

In the interim: you should work-around this, by doing both: https://github.com/stefanpenner/ember-moment/issues/80#issuecomment-130498119

and the suggested raw setTimeout + Ember.run trick.

**Comment by Iftahh** [comment]
Thank you @jasonmit  and @stefanpenner  for your quick responses and fix !

@jasonmit my code isn't open source but you should be able to reproduce it very easily -
use ember cli to generate acceptance-test and visit a page containing `moment-from-now` helper somewhere in the template - that should be enough.

**Comment by jasonmit** [comment]
3.5.1 published, take it for a spin and report if this issue persists.

**Comment by stefanpenner** [comment]
Thanks @jasonmit
