### ISSUE TITLE
Path or pattern "vendor/moment/locales/en.js" did not match any files

### ISSUE THREAD

**Issue by mydea** [stefanpenner/ember-moment#82]
I have a very strange problem. When using

```
 moment: {
    includeLocales: ["en"]
}
```

I get the error `Path or pattern "vendor/moment/locales/en.js" did not match any files`

It works when I change it to `true` instead. However, somehow after repeatedly clearing tmp, bower_components, node_modules, at some point it suddenly started working again, altough I haven't really changed anything. The problem also occured on a fresh install.

**Comment by jasonmit** [comment]
What version of moment is being pulled in?

**Comment by jasonmit** [comment]
Also what version of ember cli

**Comment by mydea** [comment]
I'm using the newest versions as far as I've seen:

* ember-cli 1.13.8
* ember-moment-shim 0.6.1
* ember-moment 3.5.1

* ember 1.13.8
* moment 2.10.6
* moment-timezone 0.4.0

I installed it via `ember install`. 

(I tried it with the included moment-version 2.8.0 and with the newest 2.10.6)

**Comment by jasonmit** [comment]
I haven't been able to reproduce this, any chance you can isolate it to an example and push it to github?  Will help speed up patch time

**Comment by mydea** [comment]
I have this issue with this pretty minimal example:

https://github.com/mydea/ember-cli-example-app-for-github/tree/ember-moment

**Comment by jasonmit** [comment]
I'm not seeing the error, perhaps its an issue with your npm packaging cache?

**Comment by mydea** [comment]
I deleted the tmp, node_modules and bower_components folder, ran the following commands:

```
npm cache clean
bower cache clean
npm install
bower install
ember g ember-moment
```

and it still threw the same error.

**Comment by redpist** [comment]
Hi.
It seems to be an error in ember-cli-moment-shim (a major dependency of ember-moment).
Files related to the included locales are directly imported from the moment 'locales' folder:
https://github.com/jasonmit/ember-cli-moment-shim/blob/d2e4f5205979b681f7118d31f50543fc16dd9c68/index.js#L42
but the 'en' locale is "almost-hardcoded" in moment.js and not present in the locale folder : 
https://github.com/moment/moment/tree/develop/locale
To bypass this problem, you can omit the 'en' locale in includeLocales.

**Comment by jasonmit** [comment]
> It seems to be an error in ember-cli-moment-shim

I don't see where I'm including `en` though.  I can warn on mismatches but that's the best I can do.

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-cli-moment-shim/pull/17 will warn on mistmatches now and quietly ignore if you pass `en` since it's included by default.  Will version as 0.6.2

**Comment by jasonmit** [comment]
3.6.2 fixes this, be sure you update your apps ember-cli-moment-shim dep to 0.6.2 or rerun the blueprint.
