### ISSUE TITLE
Setting locales from config file

### ISSUE THREAD

**Issue by jorgelainfiesta** [stefanpenner/ember-moment#83]
Hi,

I've been trying to configure the locale for this addon but nothing happens when I change the environmnet.js or even when I manually set the local on a helper instance. So I wonder if the documentation refers to some config file other than the default in CLI, as it points to `config.environment.js`

Thanks,
Jorge L

**Comment by jasonmit** [comment]
Not sure what the issue is, I have tests covering the functionality to confirm it's working as intended.  Can you explain your environment more?  (cli version, ember version, moment version).  Is your app public for me to review?  Did you install the addon with `ember install`?

**Comment by jorgelainfiesta** [comment]
Thanks for the reply. I found out it was my bad, sorry. I thought it wouldn't be necessary to restart the live preview server, as the observer detected the changes on the config file. But I restarted it and everything works fine now.

For the record, I am using: 

Ember: 1.13.6
Ember CLI: 1.13.7
Moment: 2.10.6
And I did use `ember install`.
