### ISSUE TITLE
Set allow-empty globally

### ISSUE THREAD

**Issue by MauriceMohlek** [stefanpenner/ember-moment#84]
It would be nice if I could set allow-empty globally.
In my application most of the dates are not well defined so i have to add to every {{moment-format}} the allow-empty=true parameter.

Since its possible to define the ouput format globally I think it should be possible to define allow-empty globally too.

**Comment by jasonmit** [comment]
There is a bug in ember around parameterless helpers.  Once that is resolved I can look into adding this.

**Comment by jcope2013** [comment]
+1, what's your thoughts on a global config like this? it can default to false, I can make a PR if wanted

```

// addon/utils/compute-fn.js

import Ember from 'ember';
import config from '../config/environment';

export default function(cb) {
  return function(params, hash) {
    if (!params || params && params.length === 0) {
      throw new TypeError('ember-moment: Invalid Number of arguments, expected at least 1');
    }

    let allowEmpty = Ember.get(config, 'moment.allowEmpty');

    const datetime = params[0];

    if(hash.allowEmpty || hash['allow-empty'])
    {
      allowEmpty = hash.allowEmpty || hash['allow-empty'];
    }

    if ([null, '', undefined].indexOf(datetime) > -1 && allowEmpty) {
      Ember.Logger.warn('ember-moment: an empty value (null, undefined, or "") was passed to moment-format');
      return;
    }

    return cb.apply(this, arguments);
  };
}

// config.environment.js
module.exports = function() {
  return {
    moment: {
      allowEmpty: true
    }
  }
};

```

**Comment by jasonmit** [comment]
That seems interesting, I'd be interested and happy to review your PR.

**Comment by MauriceMohlek** [comment]
@jasonmit well, at least I want to pass a date :) Even though its null..

**Comment by jasonmit** [comment]
Thanks @jcope2013 

I have some more changes I need to make to house keeping changes and will version tomorrow.

**Comment by jasonmit** [comment]
3.6.0 closes this.  Thanks again everyone
