### ISSUE TITLE
allowEmpty destroys format?!

### ISSUE THREAD

**Issue by MauriceMohlek** [stefanpenner/ember-moment#89]
Now that allowEmpty can be set in global config it wont accept the global config for date format.

``` javascript
// environment.js 
moment: {
  outputFormat: 'DD.MM.YYYY',
  allowEmpty: true
},
```
``` hbs
// template.hbs
{{moment-format model.someDate}}
```

This will result in Friday, August 14, 2015 12:00 AM
It should print 14.08.2015.

I worked before the update, except from the allowEmpty which is working now :p

Can anybody confirm this? Am I missing something?

**Comment by MauriceMohlek** [comment]
removing allowEmpty from global config doesnt fix the formating.. 
Passing 'DD.MM.YYYY' in the hbs works. So it just dont read from global config anymore

**Comment by jasonmit** [comment]
I don't think they're related, I rewrote a large chunk and might have introduced something

**Comment by jasonmit** [comment]
what version of ember?

**Comment by MauriceMohlek** [comment]
sadly 1.13.8 due to deprecation stuff ...

**Comment by jasonmit** [comment]
That's fine, that's actually ideal right now.  I'll work on fixing it now.

**Comment by MauriceMohlek** [comment]
Another thing I discovered is when passing a null date.
the readme says If null, undefined, or an empty string as a date to any of the moment helpers then you you will Invalid Date in the output. To avoid this issue globally, you can set the option allowEmpty which all of the helpers respect and will result in nothing being rendered instead of Invalid Date.

In fact it renders the current date.

**Comment by jasonmit** [comment]
> Another thing I discovered is when passing a null date.

I can't reproduce this one

**Comment by MauriceMohlek** [comment]
Hm .. Might be an other interesting thing in the ember universe :)
But since I can set allowEmpty it doesnt kill me anymore.

**Comment by jasonmit** [comment]
3.6.1, if you can show me an example of the null rendering the current date I'd like to try and see what is going on there but tried it on all the helpers and I'm seeing Invalid Date as expected when allowEmpty is false in the global config

**Comment by MauriceMohlek** [comment]
I cant provide an example since my project is from my company and this would break some copyright shit and so on :-/
But i can tell you the way I go :)

I am using ember data to get, as you expect, data from my api.
if a date is not set my api wont return the field. So the field should be null / unset.

my global config looks like above. And so the hbs.

I will try to get an example with mirage running later at home.

**Comment by jasonmit** [comment]
If you can isolate the issue and shoot me an example that would be awesome.  I don't use ember-data much these days and would probably spin my wheels a bit trying to reproduce it.

**Comment by MauriceMohlek** [comment]
Nice i didn't knew the {{log}}. I'm quiet new to ember ^^

{{log model.someDate}} produces:

Wed Jun 26 2013 00:00:00 GMT+0200 (Westeuropäische Sommerzeit)
Mon Jun 10 2013 00:00:00 GMT+0200 (Westeuropäische Sommerzeit)
3x undefined

The 3 undefined "dates" are the one which will produce the current date.
I will try to setup an empty reproducing project and leave you a message.

Thanks so far.
