### ISSUE TITLE
Can't load Timezones

### ISSUE THREAD

**Issue by jamesdixon** [stefanpenner/ember-moment#93]
Hi,

I'm attempting to load a list of zone names using `moment.tz.names()` and keep receiving an `undefined` error when calling the aforementioned method. Using devtools, it appears moment is defined, but `tz` is not. I've added the following to my `environment.js` file:

```javascript
moment: {
    includeTimezone: 'all'
}
```
I'm calling `moment.tz.names()` through a service:

```javascript
import Ember from 'ember';
import moment from 'moment';

export default Ember.Service.extend({
  us: Ember.computed(() => {
    return moment.tz.names();
  })
});
```

I'm using `ember-moment@3.6.1` and `ember-cli-moment-shim@0.6.1` with `ember@1.13.8`. 

Thanks for the help!
James

**Comment by jamesdixon** [comment]
Also, I did run `ember g ember-cli-moment-shim` with no success.

**Comment by jasonmit** [comment]
Any chance this project is open source or can you reproduce it with an example app?

I've tried but it's working as intended for me.

**Comment by jamesdixon** [comment]
Unfortunately, it's not open source and I just created a fresh app using the same setup with a service and it worked. Damn - I hate bugs like this!

**Comment by jamesdixon** [comment]
I inspected my `vendor.js` file and I can't find any reference to `moment-timezone` so something is definitely preventing it from loading.

**Comment by jasonmit** [comment]
Hmm, yeah I'm not sure if neither of us can reproduce it on a fresh app tells me it's something specific to your app.  I can only tell you were to inspect if I can't see it myself.  

 I assume you blew away node_modules and bower_components?  And you did install ember-moment via 'ember install ember-moment'?

**Comment by jasonmit** [comment]
Closing for not being able to reproduce and inactive.

**Comment by jamesdixon** [comment]
@jasonmit sorry for never getting back to you on this. I was investigating using moment-timezone in our application, but hadn't quite gotten to a point where i _needed_ it quite yet.

That said, I'm at the point where I'm ready to start implementing timezone support. I went ahead and blew away everything in `node_modules/` and `bower_components`, removed the dependencies in `bower.json` and `package.json`, then ran `ember install ember-moment`. Unfortunately, I'm still running into the same issue. The only thing that's changed since then is that I've upgraded to ember 2.x.

If I was to give you access to our repo, would you be willing to take a quick look?

Just as a quick test, I was doing the following in our `login` route that is the first thing seen when booting up the application:

```javascript
import Ember from 'ember';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';
import moment from 'moment';

export default Ember.Route.extend(UnauthenticatedRouteMixin, {
  beforeModel() {
    let d = moment('2012-04-01 00:00:00-00');
    console.log(d.tz('America/Los_Angeles').format('ha z'));
  }
});
```

Unfortunately, I still receive a similar error:

![image](https://cloud.githubusercontent.com/assets/110114/10436133/c6a261a6-70e1-11e5-8796-c1ab0cfdbe1a.png)

Let me know if you'd be willing to take a peek as I'm currently stuck. Hopefully, it's just something stupid on my part :)

Thanks in advance,
James

**Comment by jamesdixon** [comment]
@jasonmit sorry to keep pestering you on this one, but I tracked down the issue to a conflict with [ember-cli-full-calendar](https://github.com/icicletech/ember-cli-full-calendar), which is a wrapper for Fullcalendar, which also uses Moment. Removing the addon allows Moment Timezone to function properly. Wasn't sure if you could peek at that plugin and see if you saw anything right off the bat that would cause a problem. I'm going to contact the author as well. Thanks!

**Comment by jasonmit** [comment]
https://github.com/icicletech/ember-cli-full-calendar/blob/master/index.js#L10

it's the same problem with https://github.com/stefanpenner/ember-moment/issues/110

**Comment by jamesdixon** [comment]
Thanks @jasonmit! That worked perfectly!

**Comment by jasonmit** [comment]
:+1:
